- features/configuration_loading.feature
- features/step_definitions/reek_steps.rb
- features/support/hooks.rb
- spec/samples/configuration_loading/minimal_dirty.rb
- spec/samples/configuration_loading/reek-test-run-disable_smells.reek
- spec/samples/configuration_loading/reek-test-run-enable_smells.reek
After we had merged #356 I realized that while the new way of configuration loading was tested with unit tests, there certainly was an integration spec missing. This PR introduces a proper integration which I believe covers most if not all use cases.
> Add integration test for configuration loading.

- reek.gemspec
The current unparser version 0.1.17 doesn't work with ruby 1.9.3 anymore:
Gem::InstallError: unparser requires Ruby version >= 2.0.0.
An error occurred while installing unparser (0.1.17), and Bundler cannot continue.
Make sure that `gem install unparser -v '0.1.17'` succeeds before bundling.
> Fix unparser issue with ruby 1.9.3. by pinning unparser to 0.1.16.

- CHANGELOG
- README.md
- lib/reek/cli/input.rb
- lib/reek/cli/options.rb
Implement #222 
The changes for this feature were pretty minimal, but then rubocop rightfully complained about "class too long" so I had to refactor the options class in this PR to get it green on travis.
> Run on working directory when no source is given.

- lib/reek/rake/task.rb
Avoids problem if rake task cannot find any config files.
> Do not provide -c option if no config file is found

- .travis.yml
- lib/reek/smells/smell_detector.rb
- lib/reek/source/ast_node.rb
- reek.gemspec
- spec/reek/cli/report_spec.rb
- spec/reek/core/code_context_spec.rb
- Add 2.2 to the Travis CI configuration
- Fix warnings
- Depend on unparser version that supports all relevant rubies
(#357).
> Support Ruby 2.2

- lib/reek/smell_warning.rb
- reek.gemspec
- spec/reek/smell_warning_spec.rb
This ensures the `#encode_with` method is used and YAML output is the same
on all platforms.
> Force use of Psych for YAML serialization

- lib/reek/source/sexp_extensions.rb
- spec/reek/smells/nested_iterators_spec.rb
Reek fails when super receives a block:
NoMethodError:
undefined method `method_name' for (zsuper):#<Class:0x00000003e18f90>
Shared Example Group: "common fields set correctly" called from ./spec/reek/smells/nested_iterators_spec.rb:222
> Make NestedIterator not break if iterator is called on super

- lib/reek/cli/input.rb
We use reek on Jenkins like this: `reek .`
We upgraded to the latest version and noticed that reek was suddenly not reporting anything anymore. After a lot of debugging we figured out that reek ignores the `.` we pass because it assumes we are piping Ruby code in.
I gave files given as arguments higher priority so reek only reads from `$stdin` when it is given no files.
> Fix for running reek on a build server

- lib/reek/cli/report/report.rb
- lib/reek/smell_warning.rb
- reek.gemspec
- spec/reek/smell_warning_spec.rb
So, Psych doesn't actually install on JRuby, so my previous fix didn't work for that.
Solution: Decide we're not writing a two-way converter between yaml and SmellWarning, but that instead we're writing an exporter. The result: This PR lets each SmellWarning convert to a hash with `#yaml_hash` and then calls `#to_yaml` on the resulting array.
> Fix YAML export on JRuby

- .travis.yml
- Rakefile
- Do not run rubocop task on Rubinius by default
- Add CRuby head to Travis CI config
- No longer allow build failures on Rubinius and JRuby
> Support more Rubies

- spec/reek/smells/attribute_spec.rb
- spec/reek/smells/boolean_parameter_spec.rb
- spec/reek/smells/class_variable_spec.rb
- spec/reek/smells/control_parameter_spec.rb
- spec/reek/smells/data_clump_spec.rb
- spec/reek/smells/duplicate_method_call_spec.rb
- spec/reek/smells/feature_envy_spec.rb
- spec/reek/smells/irresponsible_module_spec.rb
- spec/reek/smells/long_parameter_list_spec.rb
- spec/reek/smells/long_yield_list_spec.rb
- spec/reek/smells/module_initialize_spec.rb
- spec/reek/smells/nested_iterators_spec.rb
- spec/reek/smells/nil_check_spec.rb
- spec/reek/smells/prima_donna_method_spec.rb
- spec/reek/smells/repeated_conditional_spec.rb
- spec/reek/smells/too_many_instance_variables_spec.rb
- spec/reek/smells/too_many_methods_spec.rb
- spec/reek/smells/too_many_statements_spec.rb
- spec/reek/smells/uncommunicative_method_name_spec.rb
- spec/reek/smells/uncommunicative_module_name_spec.rb
- spec/reek/smells/uncommunicative_parameter_name_spec.rb
- spec/reek/smells/uncommunicative_variable_name_spec.rb
- spec/reek/smells/unused_parameters_spec.rb
- spec/reek/smells/utility_function_spec.rb
**What I did:**
1.) Properly scoped things. No more 
```Ruby
include Reek
include Reek::Smells
```
And the same for Reek::Core::CodeContext and so on.
2.) Fixed the formatting for heredocs, newlines, indentation and so on.
3.) Used factories were possible
4.) Fixed all calls to reek_of and friends to use symbols like this:
```Ruby
expect(src).to reek_of(:BooleanParameter)
```
**What I left to do:**
1.) I left the "@source_name" in here:
https://github.com/troessner/reek/pull/393/files#diff-ef046f7765020f5fa43c96d8361fb3bfR8
because this is something we need to fix conceptually in the shared_example
2.) I didn't fix all the requires in the smells. There's still some room left for refactoring.
> Refactor smell specs.

- lib/reek/core/code_context.rb
- spec/reek/core/code_context_spec.rb
I recently noticed a bug where a `|`-ending entry in an `exclude` config setting for a given smell would effectively exclude everything from the given smell; the below excludes _all_ methods (not just `Foo#|`) from being checked aginst `UncommunicativeVariableName`:
```yaml
UncommunicativeVariableName:
exclude:
- Foo#|
```
Today I noticed a bug where a `[]`-ending entry blows up the whole tool; the below makes Reek not work at all:
```yaml
UncommunicativeParameterName:
exclude:
- Bar#self.[]
```
I tracked down the culprit of both of these cases – the excludes were treated as regular expressions rather than straight strings.
> Escape Regexp-like Strings on CodeContext matches

- Gemfile
This will allow switching to, e.g., JRuby locally and not have to remove `:local_development` from the bundle.
> Only install byebug where it compiles

- README.md
- features/command_line_interface/options.feature
- features/reports/json.feature
- features/step_definitions/reek_steps.rb
- lib/reek/cli/option_interpreter.rb
- lib/reek/cli/options.rb
- lib/reek/cli/report/report.rb
- spec/reek/cli/json_report_spec.rb
Includes both rspec and cucumber tests as seen on the yaml report.
_____
I needed JSON output while setting up a CI with Reek. I was using the YamlReport and `YAML.parse(output).to_ruby` to get a Hash, but I thought this could be useful for others as well.
I'm getting some 1 failure on rspec and 1 on cucumber, but they are not related to the files changed on this PR. I'm getting the same failures when pulling from master. Maybe is something on my local setup, so I thought I'll give this a try.
> Adds JSON output format

- tasks/reek.rake
Running `rake reek` on the current master blows up with the `invalid option: --quiet` error.
> Rake task: drop the no longer supported --quiet option

- lib/reek/cli/options.rb
The version command using the latest gem version fails:
>>   ( $ ) reek -v
/home/timo/.rvm/gems/ruby-2.1.1/gems/reek-2.0.1/lib/reek/cli/options.rb:125:in `block in set_utility_options': uninitialized constant Reek::Version (NameError)
from /home/timo/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/optparse.rb:1390:in `call'
from /home/timo/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/optparse.rb:1390:in `block in parse_in_order'
from /home/timo/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/optparse.rb:1346:in `catch'
from /home/timo/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/optparse.rb:1346:in `parse_in_order'
from /home/timo/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/optparse.rb:1340:in `order!'
from /home/timo/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/optparse.rb:1432:in `permute!'
from …
> Fix version command.

- README.md
- bin/reek
- features/command_line_interface/options.feature
- lib/reek/cli/application.rb
- lib/reek/cli/options.rb
- lib/reek/cli/report/formatter.rb
- reek.gemspec
@tuexss’s contribution from #414 with a passing spec:
> Small cleanup commit for more transparent help-output, moving external links http->https, and some minor typos/formatting issues.
> Tinycleanup

- lib/reek/cli/report/report.rb
- lib/reek/smell_warning.rb
JSON and YAML report formatters ignored the -U (wiki link) flag. This pull request enables all report formatters to respect this option.
> Allow all formatters to support -U (wiki links)

- lib/reek/core/method_context.rb
- lib/reek/smells/feature_envy.rb
- lib/reek/source/sexp_extensions.rb
- spec/reek/smells/feature_envy_spec.rb
Reek would record `lvar.foo` and `lvar += 4` as calls to different entities. This PR fixes this.
> Unify recorded references to lvar and lvasgn

- lib/reek/configuration/configuration_file_finder.rb
This fixes #425 but lacks test coverage.
I’m not a big fan of the [current way of testing `ConfigurationFileFinder`](https://github.com/troessner/reek/blob/706f4b734a50762e93f21c1a3182f9b8c650d7ab/spec/reek/configuration/configuration_file_finder_spec.rb), so I’d like to fix this in a separate PR (that would include coverage of bare `.reek` files).
> Recognise .reek as a valid configuration file

- lib/reek/cli/options.rb
- lib/reek/configuration/app_configuration.rb
- lib/reek/configuration/configuration_file_finder.rb
- spec/reek/configuration/configuration_file_finder_spec.rb
Just an indea, let me know what you think. Technical changes: `Options#config_file` is now a `Pathname`, `ConfigurationFileFinder` now also parses from `$HOME` up (IMHO harmless – especially when we already go up to the root from the current dir – and makes the code simpler).
> Refactor ConfigurationFileFinder and its spec

- reek.gemspec
This bumps rubocop and cucumber and cleans-up the gemspec:
* `executables` are now ‘everything that’s in `bin`’;
* `files` were (mistakenly, I think) computed as an intersection rather than the sum of the `Dir[…]` and `git ls-files` calls – as a result, things like `.rubocop.yml`, `Gemfile`, `spec/samples/masked_by_dotfile/.reek`, etc. were not in the gem;
* `homepage` is now the canonical URL for the wiki;
* `rdoc_options` are copy-pasteable to the commandline;
* `require_paths` are `['lib']` by default, so dropped;
* `rubyforge_project` dropped as RubyForge no longer exists;
* `rubygems_version` [is not supposed to be set](http://guides.rubygems.org/specification-reference/#rubygems_version);
* dependencies are cleaned-up and sorted by name.
> Clean-up gemspec and bump rubocop and cucumber

- spec/reek/configuration/configuration_file_finder_spec.rb
A minor simplification of the new `ConfigurationFileFinder` spec from #428. Apologies for not catching that yesterday.
> Simplify ConfigurationFileFinder spec a bit

- README.md
Fixes #431 – took the liberty to reformat the Tools section so it looks nicer along the way.
> README: reformat Tools and link the Atom plugin

- bin/reek
- features/step_definitions/reek_steps.rb
- lib/reek/cli/application.rb
- lib/reek/cli/command.rb
- lib/reek/cli/input.rb
- lib/reek/cli/option_interpreter.rb
- lib/reek/cli/options.rb
- lib/reek/cli/reek_command.rb
- lib/reek/cli/report/formatter.rb
- lib/reek/cli/report/heading_formatter.rb
- lib/reek/cli/report/location_formatter.rb
- lib/reek/cli/report/report.rb
- lib/reek/core/code_context.rb
- lib/reek/source/ast_node.rb
- lib/reek/source/ast_node_class_map.rb
- lib/reek/source/sexp_extensions.rb
- lib/reek/source/tree_dresser.rb
- lib/reek/spec/should_reek.rb
- lib/reek/spec/should_reek_only_of.rb
- spec/reek/cli/html_report_spec.rb
- spec/reek/cli/json_report_spec.rb
- spec/reek/cli/option_interperter_spec.rb
- spec/reek/cli/text_report_spec.rb
- spec/reek/cli/yaml_report_spec.rb
- spec/spec_helper.rb
Ok, here’s a potentially controversial one: my brain freezes for a moment (and my eyes bleed a bit) every time I read one of those class names that contain mostly-lowercased acronyms.
The only reason for spelling `ASTNode` as `AstNode` that I can think of would be if there was some class autoloading that couldn’t handle acronyms, but (a) there isn’t one and (b) even Rails 2.3 handles such cases properly (_I don’t want to speak about why I know this in 2015_).
Let me know what you think. I’ll be happy to add backward compatibility (via `AstNode = ASTNode`, etc.) if you think we need to keep it until 3.0.
> Properly capitalise acronyms in class names

- lib/reek/configuration/configuration_file_finder.rb
- spec/reek/configuration/configuration_file_finder_spec.rb
This fixes a small problem I had where removing `exceptions.reek` and then adding it again broke the ConfigurationFileFinder specs.
> Pick config file that comes first alphabetically

- config/defaults.reek
- lib/reek/smells/utility_function.rb
Fixes #441. Targeted 2.2 as per #422. This is a reopened #447. :)
> UtilityFunction: drop max_helper_calls

- README.md
This cleans up the README:
* moves things relevant to the contributing guide to CONTRIBUTING.md and links it,
* spells ‘reek’ uniformly everywhere,
* drops the teletype `reek` stylisation (I’m open to reverting this one if you’re fond of it),
* switches to a flat gem version badge,
* uses less eye-bleeding `Hash` syntax in `demo.rb`,
* changes RubyDoc.info link to the current canonical form and links to the gem’s docs, which seem to be fresher (regenerated on gem pushes, probably),
* fixes typography, capitalisation and hyphenation,
* adjusts some wording to read better.
> README and CONTRIBUTING clean-up

- lib/reek/core/smell_repository.rb
- spec/reek/core/smell_repository_spec.rb
Now and then (BUT QUITE IRREGULARLY) running specs would regenerate a different `config/defaults.reek` than the one in the repo.
Thanks to the magic of `sudo chattr +i config/defaults.reek` I pinpointed the culprit. This PR makes sure the smell types are returned in a stable order.
> Sort SmellRepository.smell_types by name

- spec/reek/configuration/configuration_file_finder_spec.rb
<del>The fact that we couldn’t match the `.reek` config file via `*.reek` globbing was growing on me, so I dove into docs and found a way.</del> It turns out the globbing doesn’t work 100% of the time in Rubinius, so this PR only adds the below:
I also fondly remember the wise words of Michael Grünewald:
> Hobby: creating bug tickets, waiting for people to find out about my home directory – which happens to contain spaces, stars and newlines.
– so I added a relevant spec.
> ConfigurationFileFinder: test magic paths

- .rubocop.yml
This cleans up the RuboCop config as per current develop state: lowers acceptable offence parameters closer to RuboCop’s defaults and removes offences the codebase no longer commits.
Let me know if you believe we should allow any of the removed offences in the future.
(Apologies for the slew of clean-up PRs, but I’m trying to get the codebase as friendly as possible before ROSSConf Vienna next weekend – and RuboCop config is one of the things I want to talk about.)
> Clean up RuboCop config

- spec/reek/configuration/configuration_file_finder_spec.rb
I keep my Vim swap files in `/tmp`, which means sometimes there are `*.reek` files there. The existence of such files makes two of the `ConfigurationFileFinder` tests fail (the _returns the file in home if traversing from the current dir fails_ test and the _returns nil when there are no files to find_ test).
This PR makes RSpec skip these tests in such cases (and report which tempfile is in the way).
> ConfigurationFileFinder spec: don’t fail on config in tempdir

- .rubocop.yml
- lib/reek/smells/smell_warning.rb
This refactors `SmellWarning#yaml_hash`, our biggest ABC metric offender.
This is an example refactoring I’d like to show for tackling RuboCop offences (and, down the road, reek smells) in a codebase.
> Refactor SmellWarning#yaml_hash and lower max ABC size by 2

- lib/reek/core/method_context.rb
- lib/reek/core/singleton_method_context.rb
- spec/reek/core/method_context_spec.rb
- spec/reek/core/singleton_method_context_spec.rb
I got curious why `SingletonMethodContext` tests are empty and came up with a clean-up of `MethodContext#envious_receivers` tests and a `SingletonMethodContext#envious_receivers` test.
> Better/new {,Singleton}MethodContext#envious_receivers tests

- .rubocop.yml
- lib/reek/smells/prima_donna_method.rb
RuboCop identified that `PrimaDonnaMethod#examine_constent` had a high
ABC size.
> Extract method to reduce ABC size

- spec/quality/reek_source_spec.rb
I'm getting a rspec deprecation warning when running
$ bundle exec rake test:quality
This is the rspec deprecation warning:
```
Deprecation Warnings:
Using `should_not` from rspec-expectations' old `:should` syntax without explicitly enabling the syntax is deprecated. Use the new `:expect` syntax or explicitly enable `:should` with `config.expect_with(
:rspec) { |c| c.syntax = :should }` instead. Called from /Users/bruno/dev/reek/spec/quality/reek_source_spec.rb:5:in `block (2 levels) in <top (required)>'.
If you need more of the backtrace for any of these deprecations to
identify where to make the necessary changes, you can configure
`config.raise_errors_for_deprecations!`, and it will turn the
deprecation warnings into errors, giving you the full backtrace.
1 deprecation warning total …
```
> Update quality spec to new rspec syntax

- spec/spec_helper.rb
`factory_girl` gem outputs a couple ruby warnings. Unfortunately, at the time
of this commit this is not yet fixed in `factory_girl` repo. We have to wait
till the gem is updated and a new version released.
Also, the gem version assertion is added so we remember to remove silencer
once `factory_girl` gem is (finally) updated.
Closes #470
> Silence factory_girl warnings

- .rubocop.yml
- lib/reek/cli/options.rb
- spec/reek/cli/options_spec.rb
If the standard output is not a TTY -- for example when piping output to a pager such as less or redirecting it into a file -- colorization should not be enabled by default.
> Do not enable colorization if stdout is not a TTY

- .travis.yml
Currently Travis waits for all builds (even allowed failures) to finish before marking the given PR green. The jruby-head build is slow ([~10 minutes now](https://travis-ci.org/troessner/reek/builds/60014081)) and is usually the bottleneck when one is waiting for the build.
This [makes Travis notify GitHub all is well](http://blog.travis-ci.com/2013-11-27-fast-finishing-builds/) as soon as all of the required build jobs pass.
> Travis: notify GitHub all is well before allowed failures finish

- lib/reek/core/examiner.rb
We would like it to be possible to checkout the reek source and simply run `bin/reek`. However, dependency issues may exist between our external dependencies. In this particular case, unparser depends on a slightly older version of parser. Rubygems will handle this correctly if unparser is required first. A slight re-ordering of our internal requires makes this happen.
There is no nice way to test this automatically, but simply running `bin/reek -v` now and again should do it.
> Ensure running bin/reek from checkout works

- lib/reek/core/reference_collector.rb
- lib/reek/sexp/sexp_extensions.rb
- lib/reek/sexp/sexp_formatter.rb
- lib/reek/sexp/sexp_node.rb
- lib/reek/smells/duplicate_method_call.rb
- lib/reek/smells/repeated_conditional.rb
- spec/reek/sexp/sexp_node_spec.rb
Major changes:
- Stopped the proliferation of methods from SexpNode across our codebase. Now just "each_node" and "find_nodes" is used for traversing the AST outside of the SexpNode. 
- Tomdoc'ed all-the-things
- Make SexpFormatter the only authority for formatting Sexp's.
> Refactor sexp.

- README.md
overcommit is a fully configurable and extendable Git commit hook
manager that includes out-of-the-box support for running reek as a Git
pre-commit hook.
> Add link to overcommit under "Tools"

- spec/reek/smells/attribute_spec.rb
as proposed in #495 here is a cleanup of the attributes spec.
i used the `ShouldReekOf` custom matcher to avoid shared specs and duplication.
is there some sort of code coverage in place?
i had to enable the Attribute smell by default to get it working with `ShouldReekOf`, is there a better way to do this?
> Cleanup attribute smell spec

- .yardopts
- docs/yard_plugin.rb
- lib/reek/core/examiner.rb
Several improvements to the YARD output:
* Include all files in `lib/`; we can exclude any classes we don't want to see by marking them `@private` or `private_constant` (I didn't know about the latter option).
* Update Examiner to use the full power of YARD.
* Include extra documentation files.
* Fix up local markdown links.
> Improve YARD output

- lib/reek/core/examiner.rb
- lib/reek/core/tree_walker.rb
- lib/reek/smells/attribute.rb
- lib/reek/smells/long_parameter_list.rb
- lib/reek/smells/smell_configuration.rb
- lib/reek/smells/smell_detector.rb
- lib/reek/smells/smell_repository.rb
- spec/reek/configuration/app_configuration_spec.rb
- spec/reek/smells/attribute_spec.rb
- spec/reek/smells/smell_configuration_spec.rb
- spec/reek/smells/smell_detector_shared.rb
- spec/reek/smells/smell_repository_spec.rb
- tasks/develop.rake
Fixes the last part of #517 and move SmellConfiguration and SmellRepository to lib/reek/smells.
Both classes are related to smells, but not to anything else in /core AFAIS.
> Move smell-related classes out of /core to /smells.

- .travis.yml
- docs/Reek-Driven-Development.md
- reek.gemspec
Resolves #527.
* Do not run tests on Ruby 1.9 anymore (Travis CI)
* Remove Ruby 1.9 specific instructions from docs
* Bump `required_ruby_version` in gemspec from `1.9.3` to `2.0.0`
What about JRuby?
> Drop support for Ruby 1.9

- features/samples.feature
- lib/reek/context/code_context.rb
- lib/reek/context/module_context.rb
- lib/reek/core/ast_node.rb
- lib/reek/smells/irresponsible_module.rb
- spec/reek/context/code_context_spec.rb
- spec/reek/smells/irresponsible_module_spec.rb
- spec/reek/source/source_code_spec.rb
Changes comment handling to only consider preceding comments as potentially descriptive. In particular, the following is not:
```
class Foo
...
end # class Foo
```
I haven't considered what to do with the following case, yet:
```
class Foo # handles bars
...
end
```
> Improve irresponsible module

- lib/reek/smells.rb
- lib/reek/smells/attribute.rb
- lib/reek/smells/boolean_parameter.rb
- lib/reek/smells/class_variable.rb
- lib/reek/smells/control_parameter.rb
- lib/reek/smells/data_clump.rb
- lib/reek/smells/duplicate_method_call.rb
- lib/reek/smells/feature_envy.rb
- lib/reek/smells/irresponsible_module.rb
- lib/reek/smells/long_parameter_list.rb
- lib/reek/smells/long_yield_list.rb
- lib/reek/smells/module_initialize.rb
- lib/reek/smells/nested_iterators.rb
- lib/reek/smells/nil_check.rb
- lib/reek/smells/prima_donna_method.rb
- lib/reek/smells/repeated_conditional.rb
- lib/reek/smells/too_many_instance_variables.rb
- lib/reek/smells/too_many_methods.rb
- lib/reek/smells/too_many_statements.rb
- lib/reek/smells/uncommunicative_method_name.rb
- lib/reek/smells/uncommunicative_module_name.rb
- lib/reek/smells/uncommunicative_parameter_name.rb
- lib/reek/smells/uncommunicative_variable_name.rb
- lib/reek/smells/unused_parameters.rb
- lib/reek/smells/utility_function.rb
- lib/reek/tree_walker.rb
- spec/factories/factories.rb
- spec/reek/smells/attribute_spec.rb
- spec/reek/smells/smell_repository_spec.rb
As per the discussion in #513, let’s just require all of the smells explicitly.
> Require smells explicitly and fix some missing require_relatives

- Gemfile
- spec/spec_helper.rb
Regarding "Fix warning": Under ruby22 the following warning would clog the screen:
```
/home/timo/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54: warning: loading in progress, circular require considered harmful - /home/timo/.rvm/gems/ruby-2.2.0/gems/pry-0.10.1/lib/pry.rb
from /home/timo/.rvm/gems/ruby-2.2.0/gems/rspec-core-3.2.3/exe/rspec:4:in  `<main>'
from /home/timo/.rvm/gems/ruby-2.2.0/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:38:in  `invoke'
from /home/timo/.rvm/gems/ruby-2.2.0/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:70:in  `run'
from /home/timo/.rvm/gems/ruby-2.2.0/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:85:in  `run'
from /home/timo/.rvm/gems/ruby-2.2.0/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:97:in  `setup'
from …
```
> Fix annoying warning under ruby22 and refactor spec set up.

- lib/reek/source/source_code.rb
Replacing #533 with a better branch name and commit message.
> Use ruby22 instead of ruby21 for parsing.

- lib/reek/ast/ast_node.rb
- lib/reek/ast/sexp_extensions.rb
- lib/reek/smells/utility_function.rb
- lib/reek/tree_dresser.rb
- spec/reek/smells/utility_function_spec.rb
Fixes #112 
The way this works is that we're passing the parent scope for each sexp to Treedresser and then store this parent scope with each adorned ASTNode.
We then check in the UtilityFunction Detector if the parent scope is of type ":sclass".
I believe this is a simple yet elegant solution.
> Recognize methods defined with class << self syntax as singleton methods.

- .travis.yml
See https://travis-ci.org/troessner/reek/jobs/67756300#L297-L307
This is really only an issue on JRUBY-HEAD where cext.enabled property no longer exists.
```ruby
expected: ""
got: "jruby: warning: unknown property jruby.cext.enabled\njruby: warning: unknown property jruby.cext.enabled\njruby: warning: unknown property jruby.cext.enabled\njruby: warning: unknown property jruby.cext.enabled\n"
(compared using ==)
Diff:
@@ -1 +1,5 @@
+jruby: warning: unknown property jruby.cext.enabled
+jruby: warning: unknown property jruby.cext.enabled
+jruby: warning: unknown property jruby.cext.enabled
+jruby: warning: unknown property jruby.cext.enabled
(RSpec::Expectations::ExpectationNotMetError)
./features/step_definitions/reek_steps.rb:58:in `/^it reports no errors$/' …
```
> Fix Travis on JRuby-HEAD using explicit opts

- .travis.yml
- docs/API.md
- lib/reek/cli/report/report.rb
- reek.gemspec
Fixes #472 
I really like ataru but it has quite some annoying limitations. 
E.g. there is not silent flag. Which is why at the end of a rake run you'll see:
```
..string -- 9 warnings:
Dirty has no descriptive comment (IrresponsibleModule)
Dirty#awful has 4 parameters (LongParameterList)
Dirty#awful has approx 6 statements (TooManyStatements)
Dirty#awful has boolean parameter 'log' (BooleanParameter)
Dirty#awful has the parameter name 'x' (UncommunicativeParameterName)
Dirty#awful has the variable name 'w' (UncommunicativeVariableName)
Dirty#awful has unused parameter 'log' (UnusedParameters)
Dirty#awful has unused parameter 'offset' (UnusedParameters)
Dirty#awful has unused parameter 'y' (UnusedParameters)
.```
Annoying, but ok for me.
> Integrate Ataru.

- lib/reek/source/source_locator.rb
- spec/reek/source/source_locator_spec.rb
- spec/samples/source_with_hidden_directories/.hidden/uncommunicative_method_name.rb
- spec/samples/source_with_hidden_directories/uncommunicative_parameter_name.rb
Fix of the first problem reported in #557:
>> files prefixed with a dot (.git)
files suffixed with a .cache
Everything. This was not the case in previous versions.
> Fix reek descending into hidden directories.

- lib/reek/source/source_locator.rb
- spec/reek/source/source_locator_spec.rb
Fixes #562 
I also refactored SourceLocator and made specifically "source_paths" simplier and more lightweight.
As soon as this merged i'll release 3.0.3
> Fix finding sources when using just the current directory.

- lib/reek/report/report.rb
- spec/reek/report/html_report_spec.rb
I got frustrated by the `Html file saved` printed on spec runs. This PR:
* properly capitalises that line (is this backward-incompatible? if so I’ll make it keep the awful case),
* uses `File.write` and side-steps a line-wrapping need in `Report::HTMLReport#show`,
* redoes the spec to use a (legibly-named) tempfile.
> Redo Report::HTMLReport#show and its spec

- features/step_definitions/sample_file_steps.rb
- features/support/env.rb
- reek.gemspec
This bumps dev dependencies to their current versions. Big shout-out to @maxmeyer for fixing https://github.com/cucumber/aruba/pull/277 on the spot and releasing aruba 0.7.2! :sparkles:
> Bump dev dependencies

- lib/reek/cli/option_interpreter.rb
- lib/reek/cli/options.rb
- lib/reek/report.rb
- spec/reek/cli/option_interpreter_spec.rb
- spec/reek/cli/options_spec.rb
Re-targeted version of #552.
- Delegate option mapping from OptionInterpreter to Report
- Demand a valid option to be passed instead of relying on defaults
> Move report option mapping into Report

- .travis.yml
Ok, this one might be controversial, but here goes: I think reek 3 should support JRuby 9.0.0.0 (even though it’s not released yet) rather than JRuby 1.7.
In my opinion one of the main reasons we dropped Ruby 1.9 support in reek 3 was to be able to use Ruby 2.0 syntax, from keyword arguments to things like `__dir__`. JRuby 1.7 supports only Ruby 1.9 syntax (and features), while JRuby 9.0.0.0 supports Ruby 2.2 syntax (and features) – so if we want to support JRuby 1.7 in reek 3 then using Ruby 2.0 features would have to wait for reek 4.
> Target JRuby 9.0.0.0 (rather than JRuby 1.7)

- lib/reek/ast/node.rb
- lib/reek/ast/object_refs.rb
- lib/reek/context/method_context.rb
- lib/reek/context/singleton_method_context.rb
- lib/reek/smells/feature_envy.rb
- spec/reek/ast/object_refs_spec.rb
- spec/reek/context/method_context_spec.rb
- spec/reek/smells/feature_envy_spec.rb
This makes `ObjectRefs` collect `ObjectRef` objects, which track the callsite lines, and makes `FeatureEnvy` use it to fix #480.
> ObjectRefs: track lines for FeatureEnvy

- features/step_definitions/sample_file_steps.rb
- lib/reek/cli/options.rb
- lib/reek/configuration/app_configuration.rb
- lib/reek/configuration/configuration_file_finder.rb
- lib/reek/report/report.rb
- lib/reek/source/source_code.rb
- lib/reek/source/source_locator.rb
- spec/reek/configuration/app_configuration_spec.rb
- spec/reek/configuration/configuration_file_finder_spec.rb
- spec/reek/report/xml_report_spec.rb
- spec/reek/source/source_locator_spec.rb
- spec/spec_helper.rb
This:
* uses `__dir__` wrapped in a `Pathname` instead of `File.expand_path` (where possible),
* makes `AppConfiguration.load_from_file` take a `Pathname` instead of a `String` (is this a backward-incompatible change? I can make it take either…),
* makes `AppConfiguration.exclude_paths` return `Array<Pathname>`,
* makes `SourceLocator#sources` return `Array<Pathname>`,
* uses `Kernel.Pathname` (rather than `Pathname.new`) consistently throughout the codebase.
Once we drop Ruby 2.0 and 2.1 support we can start using the nicer-looking `Pathname#/` instead of `Pathname#+` and `Pathname#write` instead of `File.write`.
Fixes #555.
> Use Pathnames where possible

- lib/reek/source/source_locator.rb
This might not be as readable as it should, [as per this comment](https://github.com/troessner/reek/pull/596#discussion_r34425701), so let’s drop it. :)
> SourceLocator: drop Method#to_proc’s cleverness

- lib/reek/ast/sexp_extensions.rb
- lib/reek/context/code_context.rb
- lib/reek/context/method_context.rb
- lib/reek/context/root_context.rb
- lib/reek/smells/smell_repository.rb
- lib/reek/smells/utility_function.rb
- lib/reek/tree_walker.rb
- spec/reek/context/code_context_spec.rb
- spec/reek/smells/utility_function_spec.rb
- spec/reek/tree_walker_spec.rb
This fixes #582.
To be able to track calls to module_function in all cases, these calls are handled during the walking of the tree by TreeWalker. Parent contexts track the currently set visibility and pass it on to any new child contexts. If module_function is used with arguments, the parent context will instead modify the visibility of existing children.
In order to have the final visibility at hand while detecting smells, the smell detection is done after the entire tree has been walked.
Next steps:
* Move smell detection phase out of TreeWalker
* Change Attribute to use this same mechanism.
> Handle modifier style use of module_function for UtilityFunction

- features/step_definitions/sample_file_steps.rb
- lib/reek/cli/options.rb
- lib/reek/configuration/app_configuration.rb
- lib/reek/configuration/configuration_file_finder.rb
- lib/reek/report/report.rb
- lib/reek/source/source_locator.rb
- spec/reek/configuration/app_configuration_spec.rb
- spec/reek/configuration/configuration_file_finder_spec.rb
- spec/reek/examiner_spec.rb
- spec/reek/report/xml_report_spec.rb
- spec/reek/source/source_locator_spec.rb
- spec/reek/spec/should_reek_of_spec.rb
- spec/reek/spec/should_reek_spec.rb
- spec/spec_helper.rb
Four changes requested by @mvz in a post-merge review of #596:
* `Pathname` → `Pathname.new` switch,
* proper expansion of `$HOME` for Aruba-based features,
* single `flat_map` call in `SourceLocator#initialize`,
* switching all specs to (once-computed) `SAMPLES_PATH`.
I’ll do the ‘`SourceCode.from` should just take `IO` objects’ in a separate PR.
As these are four fairly disjunct fixes I made four commits; let me know if that’s too many because `<%= reasons %>`. ;)
> Pathname switch fixes

- lib/reek/ast/sexp_extensions.rb
- lib/reek/context/code_context.rb
- lib/reek/context/module_context.rb
- lib/reek/smells/duplicate_method_call.rb
- lib/reek/smells/irresponsible_module.rb
- lib/reek/tree_walker.rb
- spec/reek/ast/sexp_extensions_spec.rb
- spec/reek/smells/irresponsible_module_spec.rb
Introduces a new ModuleContext for classes defined by constant assignment, like so:
```ruby
Foo = Class.new do
def bar(a, b)
end
end
```
This means smells on methods inside the class definition will have the correct context reported.
Also makes IrresponsibleModule detect when such classes have no comment. Other smells still have to be adjusted to consider :casgn contexts.
This makes reek handle the following sample code (from #341) correctly:
```ruby
module A
B = Struct.new(:c) do
def initialize
end
def foo(a, b)
end
end
end
```
> Handle casgn style class definitions

- CHANGELOG.md
- spec/gem/yard_spec.rb
This PR fixes a `yardoc` warning, reimplements its call’s spec and checks the call for a successful return.
(Interestingly, we don’t seem to ever execute it, as we only ever run `spec/reek/**/*_spec.rb` files.)
> Reimplement yardoc spec and fix a warning

- lib/reek/configuration/app_configuration.rb
- lib/reek/smells/smell_repository.rb
- lib/reek/source/source_locator.rb
- reek.gemspec
Current master is no longer warning-clean, as it started throwing warnings about private attributes (don’t get me started how wrong the warning is).
This makes this warning go away by using the private_attr gem. This also includes some related refactorings of `SmellRepository`.
> Use private_attr to silence ‘private attribute?’ warnings and refactor SmellRepository a bit

- README.md
Fixes #529 
Testing this configuration on a commercial project:
Helpers:
```
( $ (master)) reek  app/helpers/ | wc -l
116
( $ (master)) reek -c /tmp/config.reek app/helpers/ | wc -l
35
```
Controllers:
```
( $ (master)) reek  app/controllers/ | wc -l
120
( $ (master)) reek -c /tmp/config.reek app/controllers/ | wc -l
38
```
> Add Rails-friendly mode to README.

- lib/reek/report/report.rb
- spec/reek/report/xml_report_spec.rb
- spec/samples/checkstyle.xml
So I wanted to make the spec for `XMLReport` a bit more readable and parallelisable (fewer indirections, no `File` stubbing) and ended up with a new `XMLReport` that’s a bit more object-oriented and builds the output lazily rather than procedurally.
Notable changes:
* when a smell is reported for multiple lines we now include a separate `<error>` for every line;
* the XML is now human-readable.
I don’t think they are backward-incompatible, but I’ll reopen against `reek-4` if you believe so.
I’ll squash this one after a review. :)
> I accidentally the whole XMLReport

- config/defaults.reek
- docs/Attribute.md
- features/samples.feature
- lib/reek/smells/attribute.rb
- spec/reek/smells/attribute_spec.rb
Follow-up for #574.
This one cleans things up and adds support for `attr :foo, true`.
I've left @beanieboi's work, with some trivial fixes to make the build green, in a separate commit.
I'd like to unify the visibility handlers, but I'll leave that for a separate PR.
> Attributes smell no readers

- features/step_definitions/sample_file_steps.rb
- reek.gemspec
This bumps Aruba to 0.8 and fixes our step definitions to make it green (and not spew deprecation warnings). Hopefully it also fixes JRuby build. ಠ_ರೃ
> Bump Aruba

- lib/reek/ast/sexp_extensions.rb
- spec/reek/ast/sexp_extensions_spec.rb
- spec/reek/tree_walker_spec.rb
Seems that the issue is `casgn`'s value did not respond to type when `tree_walker` is trying to decide if it `defines_module?`
since it doesn't respond to type, I think it is safe to say that it does not define a module.
> Check casgn value responds to type

- lib/reek/cli/silencer.rb
This doesn't show up in our tests. Perhaps because of bundler.
> Use of StringIO requires stringio

- CHANGELOG.md
- lib/reek/code_comment.rb
This is a workaround for #653 until https://github.com/tenderlove/psych/issues/223 is fixed.
I think we should release this as `3.2.2`, so I created a `stable-3.2` branch to handle this.
> Ensure full psych is loaded

- Rakefile
- lib/reek.rb
- lib/reek/ast/node.rb
- lib/reek/ast/object_refs.rb
- lib/reek/ast/reference_collector.rb
- lib/reek/cli/command.rb
- lib/reek/cli/warning_collector.rb
- lib/reek/code_comment.rb
- lib/reek/configuration/app_configuration.rb
- lib/reek/report/formatter.rb
- lib/reek/smells/smell_configuration.rb
- lib/reek/source/source_locator.rb
- lib/reek/spec/should_reek_only_of.rb
We've always been careful to ensure each file `require`s its own requirements, but with `private_attr` we've failed to do so. This makes it hard to require individual reek files if needed.
This PR makes sure that for every file in reek's lib, `ruby -e "require '<file>'"` works.
> Ensure each file can be individually required

- .rubocop.yml
I'm sorry, but 100 characters max is driving me CRAZY.
Can we please use 120, pretty please?
> Increase rubocop's line length limit.

- docs/Code-Smells.md
I noticed that as of the latest gem that Attribute is no longer disabled by default so thought it a good idea to submit a pull request to update the docs - apologies in advance if this is not the correct procedure to adjust the docs
> Attribute no longer disabled by default

- .travis.yml
This allows Rubinius to fail, makes the config pass [the linter](http://lint.travis-ci.org) and drops extraneous quotes.
> Allow Rubinius failures and touch up Travis config a bit

- CHANGELOG.md
- config/defaults.reek
- docs/Nested-Iterators.md
- lib/reek/smells/nested_iterators.rb
- spec/reek/smells/nested_iterators_spec.rb
> Ignore `Object#tap` for NestedIterators.

- lib/reek/examiner.rb
- lib/reek/source/source_code.rb
- lib/reek/spec/should_reek.rb
> Replace the highly misleading "SourceCode#description" with "origin".

- docs/Utility-Function.md
- features/configuration_files/masking_smells.feature
- features/step_definitions/sample_file_steps.rb
- lib/reek/context/code_context.rb
- lib/reek/smells/utility_function.rb
- spec/reek/smells/utility_function_spec.rb
Related to #681 
CC'ing @isaiah @nTraum @lipanski @hwo411 @RaVbaker @tomash
After this is merged we should release 3.4. as well.
> Make UtilityFunction configurable for non-public methods.

- lib/reek/cli/application.rb
- lib/reek/cli/option_interpreter.rb
- lib/reek/cli/options.rb
- spec/reek/cli/option_interpreter_spec.rb
- spec/reek/cli/options_spec.rb
Fixes #605
Basically this removes the bad "Options#options" abstraction completely.
Now we're down to just using "Options" and "OptionInterpreter" which looks appropriate to me.
I also refactored application.rb and beefed up our specs a tad ;)
> Fix options hell in CLI namespace.

- lib/reek/ast/sexp_extensions.rb
- spec/reek/ast/sexp_extensions_spec.rb
Trying to parse Ruby’s `test/test_delegate.rb` reek blows up on the [`DC = dc.new(new)`](https://github.com/ruby/ruby/blob/v2_2_3/test/test_delegate.rb#L212) line:
```
/home/chastell/coding/reek/lib/reek/ast/sexp_extensions.rb:434:in `defines_module?': undefined method `simple_name' for (lvar :dc):#<Class:0x007fe7a2fcdb40> (NoMethodError)
```
This adds `AST::SexpExtensions::LvarNode#simple_name` to fix this.
> Add AST::SexpExtensions::LvarNode#simple_name

- lib/reek/report/location_formatter.rb
- spec/reek/report/location_formatter_spec.rb
I recently noticed that our formatters don’t sort line numbers on output.
This makes the `DefaultLocationFormatter` sort lines on output, `SingleLineLocationFormatter` output the first line and turns all `.format` methods into `module_functions`.
> LocationFormatters: sort lines in reports

- features/step_definitions/reek_steps.rb
- reek.gemspec
(That thing where you want to get back to hacking on reek, think ‘I’ll just bring deps to the current upstreams’ and spend an hour fixing Aruba deprecations.)
> Bump deps and fix Aruba 0.9 deprecations

- lib/reek/ast/sexp_extensions.rb
- spec/reek/ast/sexp_extensions_spec.rb
> SendNode: don’t blow up on arg-less attr calls

- lib/reek/smells/smell_warning.rb
- lib/reek/spec/should_reek_of.rb
- spec/reek/spec/should_reek_of_spec.rb
Fixes #599 
Actually this feature (properly checking and reacting to missing smell_details) was never implemented ;)
> Fix smell_details handling in `reek_of` matcher.

- lib/reek/ast/sexp_extensions.rb
- spec/reek/ast/sexp_extensions_spec.rb
I don’t think it’s feasible (or even possible) to statically infer whether `Foo = new` creates a `Module`, a `Class` or some other object, so this assumes this is not a module-creation call.
Fixes #715.
> ‘Foo = new’ syntax support

- lib/reek/ast/sexp_extensions.rb
- spec/reek/ast/sexp_extensions_spec.rb
Fixes #719.
I’m not 100% sure this is a good `simple_name` for a `BlockNode`, but I couldn’t come up with anything better.
We should probably have a common, minimal API all nodes are expected to implement and verify that they do. :)
> Add BlockNode#simple_name

- CHANGELOG.md
- lib/reek/version.rb
Fixes #717. :)
1. I wasn’t sure which PRs to recognise in the CHANGELOG – I went for user-visible ones.
1. Should I merge the three ‘Fix parsing’ lines into one?
> Prepare 3.4.1 release

- lib/reek/ast/node.rb
- lib/reek/ast/sexp_extensions.rb
- lib/reek/smells/boolean_parameter.rb
- lib/reek/smells/too_many_instance_variables.rb
- lib/reek/smells/uncommunicative_variable_name.rb
- lib/reek/tree_walker.rb
- spec/reek/context/code_context_spec.rb
Fixes #546
I believe "first" and "[]" were misleading, artificial and confusing abstractions that added complexity but no value.
Oh, and they **always** tripped me up.;)
> Get rid of all deprecated methods in AST::Node.

- features/support/env.rb
> Use non-deprecated method for configuring Aruba

- spec/reek/smells/smell_warning_spec.rb
This is prep for more sophisticated version that will check more than just class name and params; but assuming it's best to start with a small pull request so we can check that I'm fitting in with the way the project is currently doing things, before I go on and code lots more.
Existing discussion on this feature and the approach here: https://github.com/troessner/reek/issues/589
> adds tests for existing functionality of SmellWarning#matches? 

- lib/reek/smells/nested_iterators.rb
While working on #729 I figured that we have to refactor NestedIterators.
Why, you ask?
1.) It's spaghetti code at it's best. "find_iters" calls "find_iters_for_iter_node". Which then calls "find_iters". Which then calls "find_iters_for_iter_node". You see where I'm going with this, don't you? ;)
2.) It's not a real recursion (see [1]) which it should be, given that we are traversing trees
3.) It's very hard to read and understand. I'd call that "unmaintainable"
4.) It's not documented at all.
So, let's fix all the things!
Please find below my humble attempt to improve this.
I believe the refactoring below addresses all of the issues mentioned above and will allow us to extend NestedIterators in the future if necessary.
> Refactor NestedIterators.

- lib/reek/smells/smell_warning.rb
- lib/reek/spec/should_reek_of.rb
- spec/reek/context/module_context_spec.rb
- spec/reek/smells/attribute_spec.rb
- spec/reek/smells/boolean_parameter_spec.rb
- spec/reek/smells/control_parameter_spec.rb
- spec/reek/smells/data_clump_spec.rb
- spec/reek/smells/duplicate_method_call_spec.rb
- spec/reek/smells/feature_envy_spec.rb
- spec/reek/smells/irresponsible_module_spec.rb
- spec/reek/smells/long_parameter_list_spec.rb
- spec/reek/smells/long_yield_list_spec.rb
- spec/reek/smells/nested_iterators_spec.rb
- spec/reek/smells/smell_warning_spec.rb
- spec/reek/smells/uncommunicative_module_name_spec.rb
- spec/reek/smells/uncommunicative_parameter_name_spec.rb
- spec/reek/smells/uncommunicative_variable_name_spec.rb
- spec/reek/smells/unused_parameters_spec.rb
- spec/reek/smells/utility_function_spec.rb
- spec/reek/spec/should_reek_of_spec.rb
So this is another tiny step towards https://github.com/troessner/reek/issues/589 getting set up so that we can actually test that a smell message has changed
> adding ability to check for smell message contents

- reek.gemspec
Parser 2.2.3.0 got released and it seems Reek can use it just fine.
I’m unhappy with this PR, though: some time ago we agreed that Parser’s versioning is at odds with SemVer and – since it’s crucial to Reek’s operations – we should be strict about this dependency. That said, making us depend on `parser ~> 2.2.3.0` means that Reek can’t be used alongside tools with a Parser 2.2.2.x dependency; one could argue that this is actually a breaking change.
We know that Reek works with Parser 2.2.2.5+ and assume it’ll work with any 2.2.3.x. Maybe we should do the dependency like this?
```Ruby
s.add_runtime_dependency 'parser', '>= 2.2.2.5', '< 2.2.4'
```
> Bump Parser

- docs/API.md
- lib/reek/configuration/app_configuration.rb
- spec/reek/configuration/app_configuration_spec.rb
#662.
I decided to create a new method `.from_hash` in the end because I think this is a nicer name and we can more simply deprecate the entire `.from_map` method. We can remove `.from_map` in Reek 4.
Internally, `.from_map` is still used at the moment.
> Unify config loading

- reek.gemspec
I was running into the following error running Reek's Cucumber suite:
```
% bundle exec cucumber
cannot load such file -- rspec/support/object_formatter (LoadError)
/Users/andy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/aruba-0.9.0/lib/aruba/matchers/base/base_matcher.rb:1:in `require'
/Users/andy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/aruba-0.9.0/lib/aruba/matchers/base/base_matcher.rb:1:in `<top (required)>'
/Users/andy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/aruba-0.9.0/lib/aruba/platforms/unix_platform.rb:86:in `require_relative'
/Users/andy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/aruba-0.9.0/lib/aruba/platforms/unix_platform.rb:86:in `block in require_matching_files'
/Users/andy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/aruba-0.9.0/lib/aruba/platforms/un …
```
> Bump Aruba dependency

- features/command_line_interface/options.feature
- lib/reek/cli/options.rb
- lib/reek/report.rb
- lib/reek/report/code_climate_formatter.rb
- lib/reek/report/formatter.rb
- lib/reek/report/report.rb
- reek.gemspec
- spec/reek/report/code_climate_formatter_spec.rb
- spec/reek/report/code_climate_report_spec.rb
This commit introduces a new formatter intended for use with Code
Climate's engine platform.
https://github.com/codeclimate/spec
Further integration work will be required, but the aim is that the Reek
repository will act as the home for Code Climate's Reek engine, rather
than having a separate repository for the engine.
The core team have discussed and agreed to this approach.
> Add Code Climate JSON report format

- lib/reek/smells/module_initialize.rb
Let's face it, this comment would stick there for the next 10 years and decrease readability and confuse readers.
Let's remove it. IF we want to do this (and I don't see the point of it), we should rather discuss this in github issues, not as FIXME comments.
> Remove FIXME comment.

- lib/reek/tree_walker.rb
- spec/reek/tree_walker_spec.rb
- spec/spec_helper.rb
Ready for review!
This is a prerequisite for me in order to start refactoring TreeWalker and CodeContexts to address #775 and quite a few other issues we're having there (obscurity being the biggest one).
The diff is messy by nature unfortunately, probably makes more sense to look at the file without a diff.
What I did:
1.) Introduced specs for #initialize (un-speced before)
2.) Restructured, simplified and cleaned up our existing "statement counting" specs
3.) Introduced specs for #walk (un-speced before)
I'd appreciate a quick review @chastell && @mvz since this is kind of blocking me from further refactoring tasks.
> Spec TreeWalker properly.

- .rubocop.yml
- lib/reek/context/visibility_tracker.rb
- lib/reek/context_builder.rb
Our context building was pretty confusing.
So basically we were using the chain
inside_new_context -> new_context -> push
but we were also using `new_context` standalone (e.g. for AttributeContext). In this case however not for a new context itself, but for the sideeffect of appending a child context.
Additonally we were passing down a block 2 methods deep, something that always smells for me.
This PR cleans this up and separates concerns better which results in better readability.
> Refactor context building.

- lib/reek/code_comment.rb
- spec/reek/code_comment_spec.rb
The initial implementation was a little smelly (magic number!), a little obscure (gsub ftw) and a little messy.
> Refactor CodeComment.

- lib/reek/source/source_code.rb
- spec/reek/source/source_code_spec.rb
> Switching to keyword arguments for SourceCode initializer

- features/command_line_interface/options.feature
- features/step_definitions/reek_steps.rb
- features/step_definitions/sample_file_steps.rb
- lib/reek/cli/application.rb
- lib/reek/cli/options.rb
> Make exit codes configurable.

- lib/reek/source/source_locator.rb
Hi.
I encounter an error.
https://github.com/skyarch-networks/skyhopper/pull/180#issuecomment-169521324
I think Reek doesn't skip a path that doesn't exist.
Because, `print_no_such_file_error(given_path)` returns a `nil`. So, `&& next` is not evaluated.
I created a repository for this problem. 
https://github.com/pocke/broken-reek-repo
You can try this problem by the following procedure.
```sh
$ git clone https://github.com/pocke/broken-reek-repo
$ cd broken-reek-repo
$ reek
```
Before patch
-------
After patch
-----
> [bug fix] Skip path if path doesn't exist.

- docs/Rake-Task.md
- features/rake_task/rake_task.feature
- lib/reek/rake/task.rb
The Rake task currently insists on taking a single glob pattern, while Rake's FileList is perfectly capable of taking multiple patterns. By relaxing the type check and taking advantage of the fact that passing a `FileList` to `FileList.[]` returns the same `FileList`, we can allow developers to set a fully customized `FileList` without changing the original API.
The right place to test this is unclear to me. There are no unit tests for the Rake task, and only some integration tests. Any suggestions?
See #788.
> Accept FileList as Rake task source files

- .travis.yml
- Gemfile
- reek.gemspec
Fixes #821 with some small adjustments:
* I decided to put "development_dependencies" under the group "test" because we use them for running tests local and on travis
* I renamed "local_development" to "development"
* I removed the "yard" gem and the "redcarpet" gem. Why exactly did we have them in the first place? I can't really remember :)
Additionally I bumped `unparser` from 0.2.2 to 0.2.4 since bundler was acting up on ruby 2.1 and 2.0 for whatever reasons. I didn't investigate since this upgrade fixed it and seemed non-critical since we plan to remove `unparser` as soon as possible anyway.
> Improve our bundler and gemspec handling.

- features/command_line_interface/stdin.feature
- reek.gemspec
I want to get my pet projects that would benefit from the squiggly heredoc over to Ruby 2.3 ASAP, and for this we need to make sure Reek supports it.
To the best of my quick checks the current blockers are:
1. (the newest) parser 2.3.0.pre.6 still not supporting the new syntax,
1. (the newest) unparser 0.4.2 depending on parser `'~> 2.2.2'`.
Once the above are resolved I want to make sure Reek at least doesn’t blow up on the new syntax, but ideally addresses those parts of the new syntax it should address. ;)
> Parser 2.3 support

- lib/reek/source/source_code.rb
Kind of funny that none of us noticed ;)
Nothing broke because Parser::Ruby22 parses e.g.
>> user.&profile
just fine and the exact same way Parser::Ruby23 does.
> Use parser 2.3 in `SourceCode`.

- README.md
- defaults.reek
- features/samples.feature
- lib/reek/smells/unused_private_method.rb
- spec/reek/smells/unused_private_method_spec.rb
Fixes #844 
Regarding the "re-enable a by default deactivated smell detector for tests" I took some inspiration from the corresponding Attribute smell detector PR [here](https://github.com/troessner/reek/pull/613/files)
> Disable UnusedPrivateMethod detector by default.

- spec/reek/smells/irresponsible_module_spec.rb
Demonstrates and ensures that #583 is no longer a problem.
> Top-level dynamically created classes are detected

- docs/Feature-Envy.md
Missing dash. This one is correct https://github.com/troessner/reek/blob/master/docs/Utility-Function.md
> Fix link to Utility-Function in docs/Feature-Envy

- docs/API.md
- lib/reek/cli/command/report_command.rb
- lib/reek/cli/command/todo_list_command.rb
- lib/reek/examiner.rb
- lib/reek/spec/should_reek.rb
- lib/reek/spec/should_reek_of.rb
- lib/reek/spec/should_reek_only_of.rb
- spec/reek/examiner_spec.rb
- spec/reek/smells/feature_envy_spec.rb
- spec/reek/smells/unused_private_method_spec.rb
- spec/reek/smells/utility_function_spec.rb
Fixes #650, has #869 as precondition (specs and features pass, but rubocop complains)
> Clean up Examiner constructor.

- lib/reek/smells/control_parameter.rb
- lib/reek/smells/duplicate_method_call.rb
- lib/reek/smells/nil_check.rb
I started out with the obvious cases which are inner classes. (And yes, Ruby has them, and no, i don't care that they mean something different in other languages ;) )
Note that there are quite a few other classes where we should use `private_constant` as well like DataClump. But there the soon-to-be private classes are at package level, not scoped to the actual class that uses them. 
So I'd like to refactor those classes (especially DataClump!) before introducing `private_constant` there.
> Introduce `private_constant`.

- reek.gemspec
This is mainly so rubygems's announcement tweets will look better :smile:.
> Avoid extra whitespace in gem description

- Gemfile
Solves [pry history not working correctly under macos](https://github.com/guard/guard/wiki/Add-Readline-support-to-Ruby-on-Mac-OS-X#option-4-using-a-pure-ruby-readline-implementation)
> Add rb-readline as development dependency.

- .travis.yml
- Gemfile
WIP PR - i wanted to discuss this first before going further.
* This runs mutant against everything we marked as public api (except for version.rb) comparing it to the master branch (--since master)
* Speed: In case there are no changes of our subjects in regards to the master branch the whole mutant run takes less than 3 seconds on my machine
Missing:
* Proper rake task integration, right now it's just a wall of hard to read text in our travis configuration
cc @mbj - what do you think of this set up?
P.S.: The travis failure come from ruby 2.0 which will be gone [pretty soon anyway](https://github.com/troessner/reek/pull/869)
> Integrate mutant in our CI build.

- lib/reek/context/method_context.rb
- spec/reek/smells/unused_parameters_spec.rb
Same as #880 but now with more appropriate branch name and commit message.
Fixes #878
> Fix UnusedParameter detector for lvasgn.

- lib/reek/configuration/app_configuration.rb
- spec/reek/configuration/app_configuration_spec.rb
- spec/reek/smells/uncommunicative_module_name_spec.rb
- spec/reek/smells/utility_function_spec.rb
- spec/spec_helper.rb
Fixes the second part of #891 
Speedy review would be awesome since this blocks my rspec refactoring necessary for mutant necessary for #890
> Remove deprecated method `from_map` from AppConfiguration.

- .gitignore
- docs/Uncommunicative-Method-Name.md
- docs/Uncommunicative-Module-Name.md
- docs/Uncommunicative-Parameter-Name.md
- features/configuration_files/accept_setting.feature
- features/configuration_files/mix_accept_reject_setting.feature
- features/configuration_files/reject_setting.feature
- lib/reek/smells/uncommunicative_method_name.rb
- lib/reek/smells/uncommunicative_module_name.rb
- lib/reek/smells/uncommunicative_parameter_name.rb
- spec/reek/smells/uncommunicative_method_name_spec.rb
- spec/reek/smells/uncommunicative_module_name_spec.rb
- spec/reek/smells/uncommunicative_parameter_name_spec.rb
- spec/spec_helper.rb
Preliminary PR, fixes #886, successor of #887 (which had a bad branch name in the end)
What does this bad boy do?
Glad you asked!
* consistent handling of `reject` and `accept`
* makes both settings handle strings and regexes properly
* makes both settings handle list and single values
* tests!
* Updates and improves our documentation
Tomorrow I'll make some final tweaks and then this is ready for review!
> Fix `accept` and `reject` configuration handling.

- docs/Attribute.md
The warning message now has a slightly different format from what was specified in doc
> Update format of warning Attribute.md

- lib/reek/cli/application.rb
- lib/reek/cli/command/base_command.rb
- lib/reek/cli/input.rb
- lib/reek/cli/option_interpreter.rb
- spec/reek/cli/command/report_command_spec.rb
- spec/reek/cli/command/todo_list_command_spec.rb
- spec/reek/cli/input_spec.rb
In current master, configuration is never passed to source locator, so it uses default value:
```ruby
def initialize(paths, configuration: Configuration::AppConfiguration.default)
```
`Configuration::AppConfiguration.default` finds `*.reek` files in you app directory and uses them. Which causes problems in the following case:
If your configuration file isn't located in project root, or uses different format, like `config.reek.yml`, `exclude_paths` option would not work. But if you have `*.reek` file in your app root, reek will use `exclude_paths` from there, not from specified configuration file.
In my fix configuration is passed from `Application` down to ` Source::SourceLocator`
> Fix excluded paths for custom config formats

- README.md
The talk given by Piotr was at RubyConf Portugal, not RubyConf Porto. :)
> Corrects the name of the conference

- lib/reek/source/source_code.rb
This has no functional effect at the moment, but may influence implementation of future features. 
#924.
> Use parser's preferred lambda representation

- .travis.yml
By using this setting, we can turn building for pushes back on in Travis CI, so we can have an actual build history for master.
> Allow building branches only for the master branch

- lib/reek/smells/data_clump.rb
- lib/reek/smells/duplicate_method_call.rb
- lib/reek/smells/long_parameter_list.rb
- lib/reek/smells/long_yield_list.rb
- lib/reek/smells/nested_iterators.rb
- lib/reek/smells/repeated_conditional.rb
- lib/reek/smells/smell_configuration.rb
- lib/reek/smells/smell_detector.rb
- lib/reek/smells/too_many_instance_variables.rb
- lib/reek/smells/too_many_methods.rb
- lib/reek/smells/too_many_statements.rb
- lib/reek/smells/uncommunicative_method_name.rb
- lib/reek/smells/uncommunicative_module_name.rb
- lib/reek/smells/uncommunicative_parameter_name.rb
- lib/reek/smells/uncommunicative_variable_name.rb
- lib/reek/smells/unused_private_method.rb
- lib/reek/smells/utility_function.rb
- spec/reek/smells/smell_configuration_spec.rb
The fallback value is already set in the (default) configuration, so there is no need to specify it again when fetching the value.
> Remove unused fallback parameter from config handling

- .travis.yml
- features/samples.feature
- lib/reek/smells/nested_iterators.rb
- spec/reek/smells/nested_iterators_spec.rb
- spec/spec_helper.rb
Fixes #923. Nested iterator warnings with the same depth are combined, but all lines are reported.
> Report all nested iterators

- .rubocop.yml
- Gemfile
- defaults.reek
- lib/reek/cli/options.rb
- lib/reek/configuration/app_configuration.rb
- lib/reek/report.rb
- lib/reek/report/code_climate/code_climate_formatter.rb
- lib/reek/smells/data_clump.rb
- lib/reek/smells/duplicate_method_call.rb
- lib/reek/smells/long_parameter_list.rb
- lib/reek/smells/nested_iterators.rb
- lib/reek/smells/too_many_instance_variables.rb
- lib/reek/smells/too_many_methods.rb
- lib/reek/smells/too_many_statements.rb
- lib/reek/smells/uncommunicative_method_name.rb
- lib/reek/smells/uncommunicative_module_name.rb
- lib/reek/smells/uncommunicative_parameter_name.rb
- lib/reek/smells/uncommunicative_variable_name.rb
- spec/reek/report/code_climate_formatter_spec.rb
This upgrades RuboCop to version 0.40 and fixes newly detected offences.
I have chosen to configure Style/MultilineMethodCallBraceLayout with the style same_line since that matches most of our code and looks better to me.
> Upgrade RuboCop

- Gemfile
I don't think we particularly need version `4.2.7.rc1`.
> Loosen activesupport dependency

- README.md
- spec/spec_helper.rb
Alternative for #967.
I'll still add the README bit.
> Allow disabling spec Timeout for debugging

- lib/reek/cli/options.rb
- spec/reek/cli/application_spec.rb
This is checked elsewhere with a proper custom exception.
Mutant doesn't like this one :laughing:.
> Remove file existence test

- lib/reek/configuration/app_configuration.rb
- spec/reek/configuration/app_configuration_spec.rb
Since `AppConfiguration.default` is effectively the same as `AppConfiguration.new`, we can safely implement one using the other and stop hiding `.new`.
> Stop hiding AppConfiguration.new

- lib/reek/report.rb
- spec/reek/report_spec.rb
- `Hash#fetch` already raises if the key is not found, which is enough for a non-public API.
- These exceptions were untested
To allow mutant to check this properly, I had to remove `module_function`. See https://github.com/mbj/mutant/issues/459.
> Remove guard exceptions from Reek::Report

- tasks/mutant.rake
Specifying 'master^' makes sure that in most day-to-day cases, the
mutant task will find some commits to check. The is preferable to
checking for the current branch, which seems to fail on Travis.
An alternative is to use HEAD~n, for some value of n. However, this
could hide problems while a PR is being developed, while potentially
prolonging build failures on master after merging a branch that mutant
does not approve of.
> Make mutant task more robust

- tasks/test.rake
I did `git clone` the repo and tried to run test as `rake`. The result was an error because I have another version of JSON library installed:
```
/Users/soutaro/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:35:in `block in setup': You have already activated json 2.0.2, but your Gemfile requires json 1.8.3. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
```
I tried `bundle exec rake` as recommended, but did not solve the issue.
This PR is to make test setup Bundler. I'm not very sure this fix makes sense (but it works!).
> Enable bundler in test

- lib/reek/ast/sexp_extensions/send.rb
- spec/reek/ast/sexp_extensions_spec.rb
Currently `:csend` node is not supported, and the following Ruby code may make reek crash:
```rb
foo&.bar()
```
This PR is to fix the issue by adding `CSendNode`.
> Add SexpExtensions::CSendNode for safe navigation operator

- lib/reek/smells/smell_warning.rb
- lib/reek/spec/should_reek_of.rb
- spec/reek/spec/should_reek_of_spec.rb
> Fix our rspec matcher warnings to include all details.

- lib/reek/cli/options.rb
`reek --help` displays a `\n`. Because single quotation is used.
```
$ reek --help
Usage: reek [options] [files]
Examples:
reek lib/*.rb
reek -s lib
cat my_class.rb | reek
See https://wiki.github.com/troessner/reek for detailed help.
Configuration:
-c, --config FILE                Read configuration options from FILE
--smell SMELL                Detect smell SMELL (default: all enabled smells)
\nGenerate a todo list:
-t, --todo                       Generate a todo list
Report format:
-f, --format FORMAT              Report smells in the given format:
html
text (default)
yaml
json
xml
code_climate
Text format options:
--[no-]color                 Use colors for the output (default: true)
-V, --[no-]empty-headings        Show headings for smell-free source files (default: false)
-U, …
```
> Use double quotation for `\n` in --help

- Rakefile
Lgtm.
We can and should fix our mutant set up asap and then re-enable it but right now it's not working and having to check every red pull request is tedious.
> Don't run mutant on CI.

- features/reports/json.feature
- features/reports/yaml.feature
- lib/reek/smells/attribute.rb
- lib/reek/smells/boolean_parameter.rb
- lib/reek/smells/control_parameter.rb
- lib/reek/smells/data_clump.rb
- lib/reek/smells/feature_envy.rb
- lib/reek/smells/irresponsible_module.rb
- lib/reek/smells/nested_iterators.rb
- lib/reek/smells/prima_donna_method.rb
- lib/reek/smells/utility_function.rb
- spec/reek/report/json_report_spec.rb
- spec/reek/report/yaml_report_spec.rb
- spec/reek/smells/attribute_spec.rb
- spec/reek/smells/boolean_parameter_spec.rb
- spec/reek/smells/control_parameter_spec.rb
- spec/reek/smells/data_clump_spec.rb
- spec/reek/smells/feature_envy_spec.rb
- spec/reek/smells/irresponsible_module_spec.rb
- spec/reek/smells/long_parameter_list_spec.rb
- spec/reek/smells/long_yield_list_spec.rb
- spec/reek/smells/nested_iterators_spec.rb
- spec/reek/smells/nil_check_spec.rb
- spec/reek/smells/prima_donna_method_spec.rb
- spec/reek/smells/utility_function_spec.rb
Follow-up to #940 
This PR makes our parameter handling in smell warnings created in our smell detectors (`SmellDetector#inspect` to be precise) consistent.
The rule is simple (quoting @mvz 
):
>> Another way of looking at it, is that :parameters should contain all values that we interpolate into the smell warning message. No more, no less.
That's what this PR implements. On top of that a significant amount of spec changes because of `mutant`.
> Make our parameter handling consistent in smell detectors.

- lib/reek/examiner.rb
- spec/reek/examiner_spec.rb
Replacement for #1008 (it's not a breaking change anymore).
> Decouple initialization from action in Examiner.

- lib/reek/context/code_context.rb
- lib/reek/smells/too_many_instance_variables.rb
- spec/reek/smells/too_many_instance_variables_spec.rb
> Remove memoized instance variables from accounting of TooManyInstanceVariables smell

- lib/reek/spec.rb
- lib/reek/spec/should_reek_of.rb
Fixes #1027.
An alternative is to make Examiner not catch exceptions, but introduce a SafeExaminer that does and use that from the CLI.
> Do not hide exceptions in reek_of matcher

- features/samples.feature
- lib/reek/smells/smell_warning.rb
- spec/reek/smells/smell_warning_spec.rb
This is related to #1044 but I don't want to close that issue because I think it also revealed that the smell's message should be improved.
I've broken this PR into three commits:
1. Adding `#lines` to the `#sort_key` method for `SmellWarning`. If two smells share the same type, context, and message but are on different lines then I think reek should treat these as being different smells.
2. `SmallWarning` seems like a value  object to me so I renamed `#sort_keys` to `#identifying_values` because that seems to better convey the very important role that method is playing.
3. Freezing `SmellWarning` on initialization. This doesn't break any specs or public API and, if you agree that `SmellWarning` is a Value then it should forbid mutating its state. 
These are certainly opinionated changes …
> Add `#lines` to smell warning identity

- defaults.reek
- lib/reek/smells/uncommunicative_variable_name.rb
- spec/reek/smells/uncommunicative_variable_name_spec.rb
> Fix UncommunicativeVariableName does not take regex configuration into account.

- README.md
- docs/Smell-Suppression.md
- docs/Unused-Private-Method.md
- lib/reek/code_comment.rb
- spec/reek/code_comment_spec.rb
Fixes #1054 
This PR makes the ":" at the end of ":reek:UncommunicativeMethodName:" optional with 1 max
I'd consider the ":" at the end unnecessary and confusing syntax that a lot of users will get wrong.
Not to mention that a lot, a lot of people will forget about this when you go from the optionless form to the form with options like [we did ourselves](https://github.com/troessner/reek/blob/master/lib/reek/ast/node.rb#L89).
> Make our CodeComment regex more lenient.

- docs/Basic-Smell-Options.md
- docs/YAML-Reports.md
Leftover from when it was still possible to use SmellCategories.
> Remove ControlCouple as detector from docs.

- docs/Duplicate-Method-Call.md
This option was never officially documented even though we used this in our own code....
> Document `allow_calls` option for DuplicateMethodCall.

- spec/reek/cli/application_spec.rb
This may look a little weird, but on master the following fails:
```
echo 'foo' | bundle exec rake
```
This change fixes that.
> Make tests pass when run other than from a tty

- .rubocop.yml
- lib/reek/code_comment.rb
- lib/reek/errors/bad_detector_in_comment_error.rb
- lib/reek/errors/garbage_detector_configuration_in_comment_error.rb
- lib/reek/examiner.rb
- spec/reek/code_comment_spec.rb
PR nr. 3 hash-tag long-flight ;)
A typical configuration via code comment looks like this:
:reek:DuplicateMethodCall { enabled: false }
There are a lot of ways a user can introduce some errors here:
1.) Unknown smell detector
2.) Garbage in the detector configuration like { thats: a: bad: config }
3.) Unknown configuration keys (e.g. by doing a simple typo: "exclude" vs. "exlude" )
4.) Bad data types given as values for those keys
This class validates [1] and [2] at the moment but will also validate [3]
and [4] in the future.
This is basically a refactoring of the already working [1] and [2] to mitigate working on [3] and [4].
Contributes to #1102
> Introduce CodeCommentValidator.

- .rubocop.yml
- lib/reek/report/code_climate.rb
- lib/reek/report/code_climate/code_climate_fingerprint.rb
- lib/reek/report/code_climate/code_climate_formatter.rb
- spec/reek/report/code_climate/code_climate_fingerprint_spec.rb
- spec/reek/report/code_climate/code_climate_formatter_spec.rb
- spec/reek/report/code_climate/code_climate_report_spec.rb
Hi! Jumping in for @wfleming. This should close #1115.
This enables Code Climate to more accurately identify whether an issue
is new, as opposed to changed.
I chose to look at the `warning.parameters` value rather than the
`warning.message` value, because the message (for some smell types) will
change over time. For example:
If you have this code:
```ruby
class Alfa
Bravo = Charlie = Delta = 1
end
```
You will have a warning with message "Alfa has 3 constants".
Later, when you add a 4th constant, it will change to "Alfa has 4
constants".
Ideally, this would be flagged as the same Code Climate issue, but with
a greater remediation points value, so we can flag it as getting worse.
For now, I think it's good to simply treat it as the same issue.
The way this is accomplished is by …
> Emit fingerprints in Code Climate reporter

- lib/reek/report/code_climate/code_climate_fingerprint.rb
This is a follow-up to https://github.com/troessner/reek/pull/1125
Started testing this upgrade in our canary and realized that the
context where this is running, `Digest` isn't defined 😞.
While I'm here, I took the suggestion to freeze the digest from Drenmi
in the last PR. Seems sensible to me.
> Require digest for code climate reporter

- .rubocop.yml
- lib/reek/report/code_climate/code_climate_configuration.rb
- lib/reek/report/code_climate/code_climate_configuration.yml
- lib/reek/report/code_climate/code_climate_fingerprint.rb
- lib/reek/report/code_climate/code_climate_formatter.rb
- spec/reek/report/code_climate/code_climate_configuration_spec.rb
Sigh, one more (I think/hope). I forgot this was added by ActiveSupport.
It's required somewhere in the specs, so it's available outside of the
specs too, but not in the non-spec-context.
> Remove dependency on activesupport's Hash#except

- spec/reek/smell_detectors/module_initialize_spec.rb
Looking into #1137 I thought we should make this explicit also in our specs.
> Add comment spec for ModuleInitialize.

- lib/reek/context_builder.rb
- spec/reek/smell_detectors/feature_envy_spec.rb
I honestly don't know why this fixes the problem. Based on my inspection of the code, it seems like this may ensure that super is added to the context when the code is parsed so that it can be counted by the `Reek::AST::ReferenceCollector`. 
I didn't see any tests for the `CodeContext` that tested things like this so I didn't add one, but it seems like it would make sense to test these out a little bit.
It would be helpful if someone could explain what's going on here. 😄 
Per #1150
> Stop reporting FeatureEnvy with super and arguments

- .rubocop.yml
- Gemfile
- lib/reek/ast/reference_collector.rb
- spec/reek/ast/reference_collector_spec.rb
* Fixes config for MaxNesting offense
* Removes misleading spec
* Removes needless STOP_NODES
* Also updates RedCarpet.
> Update rubocop-rspec and fix offenses

- lib/reek/code_comment.rb
- spec/reek/code_comment_spec.rb
Silences warning message in our own `test:quality` rake task.
> Allow regular expressions in code comment configuration

- spec/quality/reek_source_spec.rb
This has three effects:
- Feedback is much nicer, since RSpec will print the offending file name as part of the spec description.
- Every file will be checked, regardless of earlier failures in other files.
- Each spec takes a lot less time individually, so there's less chance of hitting the 5 second spec timeout.
> Make each check for smells a separate spec

- features/samples.feature
- lib/reek/smell_detectors/manual_dispatch.rb
- spec/reek/smell_detectors/manual_dispatch_spec.rb
Reports a single warning per method with all smelly lines instead of one warning per smell.
#1117.
> Combine lines for manual dispatch smells

- lib/reek/context_builder.rb
- spec/reek/smell_detectors/feature_envy_spec.rb
#1156.
Handling of the block is fine as it happens outside the the (z)super node.
> Ensure arguments of a :super node are processed

- .travis.yml
Test on CRuby 2.4 and newer JRuby and Rubinius.
This switches the build platform to Ubuntu Trusty, since Rubinius is no longer supported on Ubuntu 12.04.
Since Bundler 1.14 has problems with setting the ruby version, downgrade it to 1.13 before running bundle install.
> Update Travis CI build platforms

- lib/reek/cli/command/report_command.rb
- lib/reek/errors/bad_detector_configuration_key_in_comment_error.rb
- lib/reek/errors/bad_detector_in_comment_error.rb
- lib/reek/errors/base_error.rb
- lib/reek/errors/garbage_detector_configuration_in_comment_error.rb
- lib/reek/errors/incomprehensible_source_error.rb
- lib/reek/examiner.rb
- lib/reek/logging_error_handler.rb
- spec/reek/examiner_spec.rb
- spec/reek/logging_error_handler_spec.rb
This was inspired by the problem fixed by #1171: That particular problem did not result in a build failure because there was only some output during the `test:quality` task, but spec itself passed.
So, what does this do? Instead of always logging exceptions in `Examiner`, we can pass in a handler object. By default, the handler doesn't handle any exceptions so they are all re-raised. However, in the configuration used when we actually run Reek, a logging handler gets passed that handles the exception by logging it, so they exceptions are not re-raised, resulting in the original behavior in that case.
> Raise exceptions from the API

- .rubocop.yml
- Gemfile
- features/command_line_interface/stdin.feature
- lib/reek/errors/parse_error.rb
- lib/reek/source/source_code.rb
- spec/reek/source/source_code_spec.rb
To keep things consistent, also let parse errors bubble up to Examiner#run, just like config and processing errors.
> Re-raise parse errors

- .rubocop.yml
- features/todo_list.feature
- spec/reek/cli/command/todo_list_command_spec.rb
- Remove specs that duplicate specs for BaseDetector
- Avoid mocking a method on the object under test
- Narrow the spy on File
- Use Reek's own silencer instead of stream re-assignment
- Give cuke feature a name
> Improve TodoListCommand specs

- spec/reek/report/code_climate/code_climate_fingerprint_spec.rb
- Discovered these while test driving a new `rubocop-rspec` cop. :)
> Remove redundant 'it' in docstrings

- spec/spec_helper.rb
This ensures individual specs can be run using `rspec something_spec.rb`.
> Ensure Timeout is known

- README.md
From the [Rails Guides](http://guides.rubyonrails.org/action_mailer_basics.html):
> Just like controllers, any instance variables we define in the method become available for use in the views.
So I'd like to suggest to losen up the requirements for *ActionMailer* descendants by disabling [`InstanceVariableAssumption`](docs/Instance-Variable-Assumption.md) for `app/mailers`.
> Update Rails example configuration to take mailers into account

- features/command_line_interface/options.feature
- features/configuration_files/exclude_paths_directives.feature
- lib/reek/cli/application.rb
- lib/reek/cli/options.rb
- lib/reek/source/source_locator.rb
- spec/reek/cli/options_spec.rb
- spec/reek/source/source_locator_spec.rb
Closes #1196 
There is probably work to do on this (such as creating a new scenario as [@mvz suggests](https://github.com/troessner/reek/issues/1196#issuecomment-290972786)), but I wanted to get this up for review and feedback as soon as possible.
As discussed, this introduces a `--force-exclusion` flag that mirrors the behavior of Rubocop's similarly-named flag. If the config contains an `exclude_path` for `smelly_path` and  CLI is called with
`reek ./smelly_path/file.rb`
Then the behavior of Reek is unchanged and the file will be checked for smell violations
But if the CLI is called with
`reek --force-exclusion ./smelly_path/file.rb`
Then the file will not be checked and Reek will exit with 0.
There's no breaking changes in this commit and all existing tests -- Cucumber and RSpec -- …
> Implement `--force-exclusion` flag

- lib/reek/configuration/app_configuration.rb
- spec/reek/source/source_locator_spec.rb
Fixes #1202
I came at this a few different ways. First I looked at expanding all
paths when creating a new SourceLocator. That worked, but made a bunch
of tests fail because they were expecting output that contained relative
paths.
So, to fix the bug and not force a rewrite of all the tests I settled on
doing the conversion within the path_excluded method. Doing it here
ensures we're comparing two absolute paths and it prevents the expanded
paths from leaking throughout the app.
I tried implementing a feature test for this but had no success. It's
weirdly hard to get an absolute path for a file you create through
Aruba. But I'm not that familiar with Cucumber and Aruba, so maybe I'm
missing something.
> Properly handle absolute paths

- README.md
It looks reek supporting Ruby 2.4.  https://github.com/troessner/reek/blob/78a05997c06f2d68110cce9b46568164d14eb267/.travis.yml#L11
> Add Ruby 2.4 to supported rubies in README.md

- lib/reek/source/source_code.rb
- spec/reek/source/source_code_spec.rb
In Ruby 2.3 or older, the following code is not parseable.
```ruby
if (a, b = foo)
end
```
So, if the above code exists in a repository, reek crashes.
This change fixes the problem.
> Use Ruby 2.4 parser for parsing code

- lib/reek/ast/builder.rb
- lib/reek/source/source_code.rb
- spec/reek/source/source_code_spec.rb
Currently, reek crashes on a string with escape sequence incompatible with UTF-8.
For example:
`test.rb`
```ruby
"\xFF"
```
```bash
$ reek
test.rb:1:1: error: literal contains escape sequences incompatible with UTF-8
test.rb:1: "\xFF"
test.rb:1: ^~~~~~
/home/pocke/.gem/ruby/2.4.0/gems/reek-4.6.1/lib/reek/source/source_code.rb:92:in `rescue in syntax_tree': test.rb: Parser::SyntaxError: literal contains escape sequences incompatible with UTF-8 (Reek::Errors::ParseError)
from /home/pocke/.gem/ruby/2.4.0/gems/reek-4.6.1/lib/reek/source/source_code.rb:89:in `syntax_tree'
from /home/pocke/.gem/ruby/2.4.0/gems/reek-4.6.1/lib/reek/examiner.rb:110:in `syntax_tree'
from /home/pocke/.gem/ruby/2.4.0/gems/reek-4.6.1/lib/reek/examiner.rb:100:in `run'
from …
```
> Prevent from breaking on a string with escape sequence incompatible with UTF-8

- README.md
The talk recording is from RubyConfBY (not RubyConfLT) and it’s a newer version of the RubyConf Portugal talk, so there’s no need to link both. Thanks so much, though! ♥
> Fix conference talk source

- lib/reek/spec/should_reek_of.rb
As uncovered in https://github.com/troessner/reek/pull/1225#issuecomment-306000011, the reek_of matcher was still using a modified version of Examiner. However, due to the introduction of pluggable error handling in #1177 this is no longer needed.
> Remove obsolete Examiner override from matchers

- features/reports/codeclimate.feature
- features/step_definitions/reek_steps.rb
- lib/reek/smell_detectors/syntax.rb
- spec/reek/smell_detectors/syntax_spec.rb
When this is missing, the Code Climate formatter errors, because the
source is required to be a String.
> Include warning.source for syntax smells

- .rubocop.yml
- lib/reek/ast/node.rb
- lib/reek/ast/sexp_extensions.rb
- lib/reek/ast/sexp_extensions/begin.rb
- lib/reek/ast/sexp_extensions/module.rb
- lib/reek/context/module_context.rb
- spec/reek/smell_detectors/irresponsible_module_spec.rb
- Improve clarity of specs
- Only allow constant creation in namespaces
#1227.
> Improve IrresponsibleModule

- features/configuration_files/directory_specific_directives.feature
- lib/reek/context/method_context.rb
- lib/reek/smell_detectors/uncommunicative_parameter_name.rb
- spec/reek/smell_detectors/uncommunicative_parameter_name_spec.rb
An unused parameter name should also be reported as uncommunicative, unless it is explicitly marked as unused.
Fixes #1045.
Note that unused parameters marked as such that would become uncommunicative if they became used (e.g., `_foo2`), are not reported.
> Also report unused uncommunicative parameter names

- lib/reek/detector_repository.rb
- lib/reek/smell_detectors/base_detector.rb
- spec/reek/smell_detectors/irresponsible_module_spec.rb
The existing implementation used the same detector for all contexts, which resulted in constantly passing around the current context and other values as parameters. This in turn has lead to a large number of
cases of feature envy and similar code smells.
By using each detector instance for just one context, we can migrate to a design where more of the state of the ongoing detection is stored in the detector and less is passed around.
> Initialize a fresh detector for each context

- lib/reek/ast/node.rb
- lib/reek/tree_dresser.rb
This attribute is no longer used, and is also confusing because it is not an object of class Reek::AST::Node.
> Remove parent attribute of Reek::AST::Node class

- lib/reek/context_builder.rb
- spec/reek/context_builder_spec.rb
- spec/reek/smell_detectors/unused_private_method_spec.rb
- spec/reek/smell_detectors/utility_function_spec.rb
This is a run-up to handling #1207: The `private def bla` construction was completely unsupported in Reek.
> Support visibility modifier of method definition

- lib/reek/ast/sexp_extensions/send.rb
- lib/reek/context/ghost_context.rb
- lib/reek/context/module_context.rb
- lib/reek/context_builder.rb
- spec/reek/ast/sexp_extensions_spec.rb
- Inline `SendNode#arg_names`. This method was not generally useful for `:send` nodes and did not return argument names in the general case.
- Merge `ModuleContext#track_visibility` and `#track_singleton_visibility`. Having two methods actually made the code more confusing.
Fixes #1239.
> Refactor ContextBuilder#handle_send_for_modules

- lib/reek/source/source_code.rb
- spec/reek/source/source_code_spec.rb
This setting was accidentally rendered useless by the introduction of a parser builder subclass in 146a5a19178e9b978a625061d94a2ee8f7a3a1e0.
> Restore emit_lambda setting

- lib/reek/smell_detectors/prima_donna_method.rb
- spec/reek/smell_detectors/prima_donna_method_spec.rb
This improves the Prima Donna Method detector by making it report the line where the method is defined, rather than the (mostly useless) line where the class starts.
This fixes #1256.
> Make prima donna method report the method definition line

- .rubocop.yml
- Gemfile
- lib/reek/cli/options.rb
- lib/reek/configuration/configuration_file_finder.rb
- lib/reek/errors/bad_detector_configuration_key_in_comment_error.rb
- lib/reek/errors/bad_detector_in_comment_error.rb
- lib/reek/errors/garbage_detector_configuration_in_comment_error.rb
- lib/reek/errors/incomprehensible_source_error.rb
- reek.gemspec
- spec/reek/ast/sexp_extensions_spec.rb
- spec/reek/cli/application_spec.rb
- spec/reek/configuration/configuration_file_finder_spec.rb
- spec/reek/smell_detectors/base_detector_spec.rb
- spec/reek/spec/should_reek_of_spec.rb
- spec/reek/spec/should_reek_spec.rb
- spec/reek/spec/smell_matcher_spec.rb
- spec/spec_helper.rb
Noteworthy parts:
* I only corrected HeredocDelimiterNaming in `lib/`, not in `spec/`.
* I disabled InterpolationCheck and BooleanSymbol.
> Update rubocop(-rspec) and fix offenses

- .travis.yml
The code that installed an older bundler version no longer works.
> Fix build on Travis CI

- CONTRIBUTING.md
- docs/Unused-Private-Method.md
- features/configuration_via_source_comments/erroneous_source_comments.feature
- lib/reek/errors/encoding_error.rb
- lib/reek/errors/garbage_detector_configuration_in_comment_error.rb
- lib/reek/errors/incomprehensible_source_error.rb
- spec/reek/source/source_code_spec.rb
Mainly changes 'can not' to 'cannot'.
> Improve wording of exception messages and other texts

- lib/reek/examiner.rb
- lib/reek/source/source_code.rb
- spec/reek/examiner_spec.rb
- spec/reek/source/source_code_spec.rb
- Move error wrapping to Examiner
- Do not rescue ParseError since it is never raised
> Simplify error handling in SourceCode

- Gemfile
- spec/factories/factories.rb
- spec/reek/code_comment_spec.rb
- spec/reek/report/code_climate/code_climate_fingerprint_spec.rb
- spec/reek/report/code_climate/code_climate_formatter_spec.rb
- spec/spec_helper.rb
The factory_girl gem was renamed to factory_but. This PR:
* Updates our dependency
* Changes references to FactoryGirl to FactoryBot
* Simplifies calls to build by removing the module name
* Removes an unused factory
> Replace FactoryGirl with FactoryBot

- spec/spec_helper.rb
Since we don't do mutation testing, this is just a burden when we're debugging.
> Drop spec timeout wrapper

- .codeclimate.yml
- lib/reek/errors/base_error.rb
- lib/reek/errors/encoding_error.rb
- lib/reek/errors/incomprehensible_source_error.rb
- lib/reek/examiner.rb
- lib/reek/logging_error_handler.rb
- lib/reek/source/source_code.rb
- spec/reek/errors/base_error_spec.rb
- spec/reek/examiner_spec.rb
- spec/reek/source/source_code_spec.rb
This changes the error processing in Examiner so that raise wrapping error classes pick up the original exception in their `cause` attribute.
This makes error reporting when the error is not handled (e.g., when running specs during development) more compact.
> Only show long error message when exception is handled

- lib/reek/ast/node.rb
- lib/reek/ast/reference_collector.rb
- lib/reek/ast/sexp_extensions/case.rb
- lib/reek/ast/sexp_extensions/if.rb
- lib/reek/ast/sexp_extensions/logical_operators.rb
- lib/reek/ast/sexp_extensions/methods.rb
- lib/reek/context/code_context.rb
- lib/reek/context/method_context.rb
- lib/reek/context/module_context.rb
- lib/reek/smell_detectors/class_variable.rb
- lib/reek/smell_detectors/instance_variable_assumption.rb
- lib/reek/smell_detectors/nested_iterators.rb
- lib/reek/smell_detectors/too_many_constants.rb
- lib/reek/smell_detectors/uncommunicative_variable_name.rb
- lib/reek/smell_detectors/utility_function.rb
- spec/reek/ast/node_spec.rb
- spec/reek/ast/sexp_extensions_spec.rb
- spec/reek/smell_detectors/control_parameter_spec.rb
This unifies `AST::Node#each_node` and `AST::Node#find_nodes`.
Fundamentally, each_node was recursive and never skipped root, while find_nodes was non-recursive and could skip root. These properties were not reflected in the method names.
The resulting `#each_node` has slightly more complex behavior than strictly desired. It is hoped that future refactoring can remedy this.
> Unify node iterators

- .codeclimate.yml
- Gemfile
- lib/reek/configuration/configuration_file_finder.rb
- lib/reek/context/code_context.rb
- lib/reek/errors/bad_detector_configuration_key_in_comment_error.rb
- lib/reek/errors/bad_detector_in_comment_error.rb
- lib/reek/errors/encoding_error.rb
- lib/reek/errors/garbage_detector_configuration_in_comment_error.rb
- lib/reek/errors/incomprehensible_source_error.rb
I’m partial to disabling IfUnlessModifier (at least in this case).
I’m also totally open to disabling FormatStringToken, but I think this actually adds to the readability and portability of the format strings (the `format` calls no longer need to maintain strict positional order of the template format sequences).
> Bump RuboCop and fix new offences

- .travis.yml
I tried to go with `jruby-9.1` and `jruby-9.1.15`, but they  both seem to resolve to the (non-existent) `jruby-9.1.15.0200`.
It seems `2.5` installs CRuby 2.5.0-preview1 which subsequently blows up; I’ll wait till Travis supports 2.5.0 and retry then.
> Travis: Add Ruby 2.5 and peg JRuby to newest 9.1

- lib/reek/context/module_context.rb
- lib/reek/smell_detectors/module_initialize.rb
- spec/reek/smell_detectors/module_initialize_spec.rb
> Do not detect ModuleInitialize for nested dynamic classes

- README.md
Updates README with Ruby 2.5 support and running Code Climate locally, as per [this thread](https://github.com/troessner/reek/pull/1282#issuecomment-353969514).
> README fixes + Code Climate info

- lib/reek/ast/node.rb
- spec/reek/ast/node_spec.rb
> Ensure all expressions have a default #name method

- lib/reek/source/source_code.rb
- reek.gemspec
- spec/factories/factories.rb
- spec/reek/source/source_code_spec.rb
Fix #1294 
Changes
===
- Use Ruby 2.5 parser
- Update parser gem
Note
==
If Reek user can select parser version (like RuboCop's TargetRubyVersion), I think it is better.
https://github.com/bbatsov/rubocop/blob/b0ef6b4a3a3455eb40b20c9b0d32982dedb043c1/lib/rubocop/processed_source.rb#L164-L184
> Support Ruby 2.5

- Gemfile
- lib/reek/cli/command/todo_list_command.rb
- lib/reek/context_builder.rb
- lib/reek/report/code_climate/code_climate_configuration.rb
- lib/reek/smell_detectors/base_detector.rb
- lib/reek/source/source_code.rb
- Update rubocop and simplecov to their latest versions
- Correct Naming/MemoizedInstanceVariableName
- Correct Style/ExpandPathArguments
- Correct Naming/UncommunicativeMethodParamName
> Update dependencies and fix new offenses

- docs/Unused-Private-Method.md
Updated to use before_action instead of before_filter so that this doc is consistent with Rails >=5.1
> Change `before_filter` to `before_action`

- .travis.yml
- reek.gemspec
Reek works fine with rainbow 2.x. This change resolves a conflict with
dependencies of pronto.
> Loosen dependency on rainbow

- docs/Prima-Donna-Method.md
Methods don't have genders, so I'm proposing removing the reference to it as `her`.
> Remove unneeded gender reference to a method

- lib/reek/code_comment.rb
- spec/reek/context/code_context_spec.rb
- spec/reek/smell_detectors/unused_private_method_spec.rb
> Drop legacy code comment separator.

- README.md
- docs/API.md
- docs/Basic-Smell-Options.md
- docs/Code-Smells.md
- docs/How-To-Write-New-Detectors.md
- docs/Prima-Donna-Method.md
- docs/Rake-Task.md
> Fix our documentation until we release Reek 5.

- bin/reek
- docs/Command-Line-Options.md
- docs/Reek-Driven-Development.md
- features/command_line_interface/options.feature
- features/reports/json.feature
- features/reports/reports.feature
- features/reports/yaml.feature
- lib/reek/cli/command/report_command.rb
- lib/reek/cli/options.rb
- lib/reek/report.rb
- lib/reek/report/formatter.rb
- lib/reek/report/formatter/documentation_link_warning_formatter.rb
- reek.gemspec
- spec/reek/report/json_report_spec.rb
- spec/reek/report/yaml_report_spec.rb
> Replace `wiki-links` flag with `documentation` flag.

- lib/reek/configuration/app_configuration.rb
- lib/reek/spec.rb
For #1248. This fixes the API as envisioned there.
There are some remaining issues are with this code:
- AppConfiguration has a hard-coded dependency on ConfigurationFileFinder. This is hard to break since we want to be able to easily say 'use the default configuration given the current working directory'.
- ConfigurationFileFinder.find smells of ControlParameter.
However, these are internal issues that don't affect the public API, so they can be picked up later.
> Update AppConfiguration API

- lib/reek/configuration/configuration_file_finder.rb
- spec/reek/configuration/configuration_file_finder_spec.rb
> Allow only .reek.yml, not any file ending in .reek.yml

- features/command_line_interface/options.feature
- features/command_line_interface/stdin.feature
- features/step_definitions/reek_steps.rb
- lib/reek/cli/command/report_command.rb
- lib/reek/cli/options.rb
- lib/reek/examiner.rb
- lib/reek/source/source_code.rb
- spec/reek/cli/application_spec.rb
When other tools, like automatic linters within editors, run a sample
through reek, they typically do so via stdin. However, if there are reek
config exceptions to apply to that file, then reek has no way of knowing
what the original filename was, triggering false positives.
This adds an `--stdin-filename` CLI option that takes the
original filename, and passes it through to the Examiner and SourceCode
file to use as the `origin` attribute, allowing the configuration
directives to apply.
Fixes #1296 
@troessner I'm probably missing a few additional places where this might need to get additional tests. I added a cuke feature to start with, and a spec in `application_spec.rb` that passed as soon as I added the option, but before I implemented the changes in `ReportCommand` and `Examiner`. …
> Add support for --stdin-filename

- lib/reek/ast/node.rb
- lib/reek/cli/silencer.rb
- lib/reek/source/source_code.rb
- spec/reek/cli/silencer_spec.rb
- spec/reek/configuration/directory_directives_spec.rb
- spec/reek/configuration/excluded_paths_spec.rb
- spec/reek/tree_dresser_spec.rb
- spec/spec_helper.rb
This does two things:
* Make `Silencer.silently` correctly restore the original situation.
* Removes use of `Silencer.silently` where it seems no longer necessary.
> Improve silently

- lib/reek/cli/application.rb
- lib/reek/cli/command/report_command.rb
- lib/reek/cli/options.rb
- lib/reek/examiner.rb
- lib/reek/source/source_code.rb
- spec/reek/cli/application_spec.rb
- spec/reek/source/source_code_spec.rb
Cleans up interface of `Examiner.new` by pushing up setting of source code origin for stdin.
> Make SourceCode the source of truth for origin

- lib/reek/ast/sexp_extensions/case.rb
- lib/reek/ast/sexp_extensions/if.rb
- lib/reek/ast/sexp_extensions/logical_operators.rb
Simple fix for #1381. Could use some (performance) tests. Based on the research by @troessner described in https://github.com/troessner/reek/issues/1381#issuecomment-403267108.
> Improve control parameter recursion performance

- README.md
The timeout has been removed, so these instructions are now unnecessary.
> Remove outdated instructions

- Gemfile
I used pry and its debugging functionality in #1408 extensively with the changes in this pull request applied there as well and everything worked well for me. Seems like rb-readline is not necessary anymore and i'm not 100% sure why we had pry-stack_explorer in the first place.
> Clean up debugging group in our bundle.

- .simplecov
- .travis.yml
- lib/reek/logging_error_handler.rb
- spec/reek/cli/application_spec.rb
- spec/reek/cli/command/todo_list_command_spec.rb
- spec/reek/configuration/app_configuration_spec.rb
- spec/reek/configuration/configuration_file_finder_spec.rb
Fixes the JRuby build and makes it required.
> Fix JRuby build

- Gemfile
Staring from version 2.0, kramdown's GFM parser has been extracted to a separate gem, kramdown-parser-gfm.
> Update kramdown to 2.1

- docs/Reek-Driven-Development.md
This PR repairs a link in the Reek-Driven Development document.
> Use Markdown relative link to reek/spec

- .travis.yml
This setting now does nothing, see https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
> Travis: Drop outdated setting "sudo: false"

- docs/Reek-Driven-Development.md
Hi, again.
I updated the text of this article to be easier to scan. Sentences are shorter.
I also removed the section on Test::Unit assert support - it was no longer current.
---
- the section on assert referred to to_source -  this commit removed `#to_source` - https://github.com/troessner/reek/commit/6b8af4b50fae56a004cc936063e633f238d62755 - and the #sniff methods in core_extras were also removed
- I conclude the Test::Unit-style support is lower, these days
> [doc] Reek-Driven Development: Simplify English; update

- docs/Reek-4-to-Reek-5-migration.md
This PR changes a line in the documentation on upgrades from 4 to 5.
It was a typo, but I changed the whole section, changing it to use a diff instead of 2 examples.
> [docs] Avoid a typo in upgrade instructions

- README.md
- lib/reek/configuration/directory_directives.rb
- spec/reek/configuration/directory_directives_spec.rb
The code was already ready for that but escaped the potential regexp declared in the reek configuration, actually disabling regexp.
This commit fixes this by removing the call to escape.
This allows this kind of declaration in the configuration file:
\# .reek.yml
```yaml
---
[...]
"engines/.*/test/.*":
InstanceVariableAssumption:
enabled: false
UncommunicativeVariableName:
enabled: false
```
If this PR is accepted, I'll update the documentation to show this _feature_.
> Enable regex for directory directives

- lib/reek/cli/command/todo_list_command.rb
- lib/reek/smell_detectors/base_detector.rb
- lib/reek/smell_warning.rb
- spec/factories/factories.rb
- spec/reek/report/code_climate/code_climate_fingerprint_spec.rb
- spec/reek/report/code_climate/code_climate_formatter_spec.rb
- spec/reek/smell_detectors/base_detector_spec.rb
- spec/reek/smell_warning_spec.rb
- spec/reek/spec/should_reek_only_of_spec.rb
- spec/reek/spec/smell_matcher_spec.rb
* Pass smell type instead of full class to `SmellWarning#initialize`
* Simplify spec setup by skipping detector creation
> Simplify SmellWarning class

- Dockerfile
`docker build` is failing on `master`, updating ruby version fix the problem:
```
Step 13/16 : RUN bundle install --without debugging development
---> Running in 714c4e374354
fatal: Not a git repository (or any of the parent directories): .git
Warning: the running version of Bundler (1.14.6) is older than the version that created the lockfile (1.17.2). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
Fetching gem metadata from https://rubygems.org/........
Fetching version metadata from https://rubygems.org/.
Resolving dependencies...
Installing ast 2.4.0
Installing thread_safe 0.3.6
Installing ice_nine 0.11.2
Installing equalizer 0.0.11
Installing kwalify 0.7.2
Installing psych 3.1.0 with native extensions
Installing rainbow 3.0.0
Using bundler …
```
> Bump base image to a more recent ruby version

- lib/reek/source/source_code.rb
Resolves part of #1469.
* Use `Parser::CurrentRuby` for parsing
* Silence parser's verbose warnings
> Use current ruby for parsing

- .rubocop.yml
- Gemfile
- features/support/env.rb
- spec/factories/factories.rb
- spec/spec_helper.rb
- Update rubocop to 0.77.0
- Update rubocop-rspec to 1.37.0
- Update RuboCop cop names in config and suppression comments
- Autocorrect FactoryBot/FactoryClassName offenses
> Update RuboCop dependencies and fix offense

- .rubocop.yml
- .travis.yml
- README.md
- reek.gemspec
- Require 2.4 in gemspec
- Make RuboCop target 2.4
- Stop building on 2.3 and jruby 9.1 on Travis
- Build on rubinius-4 for good measure
- Update README
> Drop support for Ruby 2.3

- lib/reek/smell_detectors/data_clump.rb
- spec/reek/smell_detectors/data_clump_spec.rb
Because each detector now detects one context we don't need the extra classes anymore.
> Refactor data clump detector

- docs/Control-Couple.md
solnic.eu no longer points to the intended source.
old link is nsfw fyi.
> docs: solnic.eu -> solnic.codes

- Gemfile
The current released version of pry-byebug is incompatible with the latest version of pry. Drop pry-byebug for now and avoid silent incompatible updates in the future by setting a required version.
> Avoid conflict between pry and pry-byebug

- docs/Attribute.md
This PR improves the readability of a sentence in the docs.
> (docs) Fix grammar by dropping an "it"

- lib/reek/ast/sexp_extensions/arguments.rb
- spec/reek/source/source_code_spec.rb
Hello! 
Recently I had a problem using reek with files with new ruby 2.7 features, namely forward all syntax (`...`). 
If you run reek against file like this:
```ruby
class Something
def self.call(...)
new(...).call
end
end
```
it will fail with error
```
Source {file} cannot be processed by Reek
...
Exception message:
#<NoMethodError: undefined method `components' for s(:forward_args):#<Class:0x0000560b0d368210>>
Original exception:
/usr/local/bundle/gems/reek-5.6.0/lib/reek/ast/sexp_extensions/methods.rb:17:in `parameters'
/usr/local/bundle/gems/reek-5.6.0/lib/reek/context/method_context.rb:53:in `default_assignments'
/usr/local/bundle/gems/reek-5.6.0/lib/reek/smell_detectors/boolean_parameter.rb:23:in `sniff'
/usr/local/bundle/gems/reek-5.6.0/lib/reek/smell_detectors/base_detector.rb:44 …
```
> Add node for forward_args

- README.md
Example of configuration in README was broken in [this commit](https://github.com/troessner/reek/commit/421990de37c74e6afee2e431c9eff5ffbb618e4e#diff-04c6e90faac2675aa89e2176d2eec7d8L339), erasing directory configuration.
> Fix example of reek configuration in docs

- Gemfile
- features/support/env.rb
- lib/reek/spec/smell_matcher.rb
- spec/factories/factories.rb
- spec/reek/code_comment_spec.rb
- spec/reek/report/code_climate/code_climate_configuration_spec.rb
- spec/reek/report/code_climate/code_climate_fingerprint_spec.rb
- spec/reek/report/code_climate/code_climate_formatter_spec.rb
- spec/reek/report/location_formatter_spec.rb
- spec/reek/smell_detectors/base_detector_spec.rb
- spec/reek/smell_warning_spec.rb
- spec/reek/spec/should_reek_of_spec.rb
- spec/reek/spec/should_reek_only_of_spec.rb
- spec/reek/spec/smell_matcher_spec.rb
- spec/spec_helper.rb
This replaces our FactoryBot factories with simple methods. This allows us to drop dependency on FactoryBot, and, finally, after one minor change, on ActiveSupport.
The reason to do this now is that FactoryBot does not work on Ruby 2.8.0-dev, due to the existing warnings becoming errors.
The reason to do this at all rather than wait for FactoryBot to catch up, is that I've long disliked the development dependency on ActiveSupport, which causes methods to be available on core classes that may not be available to Reek at runtime. This can cause Reek to break without our tests catching it. By removing ActiveSupport as a dependency, we take away one source of such problems.
> Remove FactoryBot and ActiveSupport dependencies

- .rubocop.yml
- reek.gemspec
It is no longer possible to set these via the rubygems.org interface. Instead, these should now be set in the gemspec. Wiki and mailing list are omitted since the former is disabled and the latter hasn't seen
activity since 2012.
See https://blog.rubygems.org/2019/03/08/and-then-there-was-one-metadata-links.html for more info on the metadata UI removal.
Fixes #1536.
> Set link metadata in gemspec

- docs/Boolean-Parameter.md
- lib/reek/report/code_climate/code_climate_configuration.yml
Reek caught this smell in my code, so I figured I'd pay it back with a
contribution!
> docs("Boolean Parameter" smell): fix typo

- .travis.yml
- Silences warnings about deprecated --client flag
- Improves startup time by using development mode
> Override TravisCI's default JRUBY_OPTS environment variable

- Gemfile
- reek.gemspec
This loosens dependencies on cucumber and simplecov so we use the most recent versions on Ruby 2.5 and up, but can still run the build on Ruby 2.4.
Additionally, the runtime dependency on psych is loosened to allow the latest version but not force users to upgrade.
> Loosen dependencies

- Gemfile
- README.md
- features/configuration_files/schema_validation.feature
- features/step_definitions/sample_file_steps.rb
- lib/reek.rb
- lib/reek/configuration/directory_directives.rb
- lib/reek/context/module_context.rb
- lib/reek/smell_detectors/boolean_parameter.rb
- lib/reek/smell_warning.rb
- spec/performance/reek/smell_detectors/runtime_speed_spec.rb
- spec/quality/documentation_spec.rb
- tasks/configuration.rake
- Updates rubocop to 0.91.0
- Updates rubocop-performance to 1.8.0
The existing implementation would pass a string to Reek::Examiner, causing the number of reported smells to be zero. It also needlessly iterated over non-source entries. This is fixed by:
- Passing a Pathname object to Reek::Examiner
- Using globbing to generate a list of Ruby files to examine
- Ensure yml extension is used everywhere
- Fix wording in README
This moves `DEFAULT_SMELL_CONFIGURATION` into `lib/reek.rb` so we can use it in the cucumber scenario.
> Update RuboCop and fix detected problems

- Gemfile
Our simplecov dependency specification seems to be too complex for dependabot to update.
> Loosen dependency on simplecov

- docs/Boolean-Parameter.md
Correct the spelling of 'altogether'
> Fix typo (alltogether → altogether)

- reek.gemspec
This updates the dependency on parser to ~> 3.0.0.
Allowing parser 3.0 is necessary to allow concurrent installation with RuboCop 1.8.0.
Versions below 3.0 are disallowed because:
- On Ruby 3.0, users should not install Parser versions below 3.0, since they do not officially support 3.0's syntax.
- Parser 3.0 supports all versions of Ruby that Reek supports.
Fixes #1576
> Require parser 3.0

- .github/workflows/ruby.yml
RuboCop is run in a separate job so don't duplicate this effort.
> Do not run RuboCop in the GitHub Action test job

- CHANGELOG.md
Simple typo, there are two 6.0.3 version headers in the file, clearly the earlier one was supposed to be 6.0.2
> Fix duplicate 6.0.3 header (should be 6.0.2) in CHANGELOG.md

- Gemfile
Version 4.0 is still needed for Ruby 2.4.
> Widen range of allowed cucumber versions

- Dockerfile
There was an issue when was trying to build the docker image. This fix adds the developer tools to the image.
`#12 3.786 You have to install development tools first.`
Complete error:
[Docker build error.txt](https://github.com/troessner/reek/files/6384623/Docker.build.error.txt)
> Add build-base to Dockerfile

- bin/code_climate_reek
This change fix 2 bugs when we analyze the code using `codeclimate`.
1. Ignored paths were analyzed ex: `bd/` `test/` 
2. There are duplicated results
**Results before remove the line**
```
== app/channels/application_cable/channel.rb (2 issues) ==
2: ApplicationCable::Channel has no descriptive comment [reek-test]
2: ApplicationCable::Channel has no descriptive comment [reek-test]
== app/channels/application_cable/connection.rb (2 issues) ==
2: ApplicationCable::Connection has no descriptive comment [reek-test]
2: ApplicationCable::Connection has no descriptive comment [reek-test]
== app/controllers/application_controller.rb (2 issues) ==
1: ApplicationController has no descriptive comment [reek-test]
1: ApplicationController has no descriptive comment [reek-test]
== …
```
> Fix bugs when is used by codeclimate

- lib/reek/code_comment.rb
- reek.gemspec
The psych gem is included by default in all Ruby versions supported by Reek. Remove it as an explicit dependency, to stop Reek from pulling in Psych 4, which has incompatible changes.
Fixes #1606.
> Remove explicit psych dependency

- .github/workflows/ruby.yml
- .rubocop.yml
- lib/reek/smell_warning.rb
- reek.gemspec
- spec/reek/rake/task_spec.rb
- Bump minimum Ruby version in gemspec
- Bump target Ruby version in RuboCop configuration
- Drop Ruby 2.4 from the matrix in the GitHub Action
- Autocorrect new RuboCop offenses
> Drop support for Ruby 2.4

- .github/workflows/ruby.yml
- .rubocop.yml
- README.md
- lib/reek/ast/sexp_extensions/case.rb
- lib/reek/ast/sexp_extensions/if.rb
- lib/reek/ast/sexp_extensions/send.rb
- lib/reek/context_builder.rb
- reek.gemspec
With the release of JRuby 9.3.0.0, we can drop compatibility with Ruby 2.5.
- Require Ruby 2.6 or higher in the gemspec
- Update RuboCop configuration and fix new offenses
- Update set of Rubies in CI
> Drop support for Ruby 2.5

- lib/reek/ast/sexp_extensions/arguments.rb
- spec/reek/smell_detectors/unused_parameters_spec.rb
This adds support for the :kwnilarg AST node.
Keyword nil arguments indicate only empty lists of keyword arguments will be accepted, so by definition such an argument can never be used.
Fixes #1666.
> Add support for keyword nil arguments

- bin/code_climate_reek
Related issue: #1687
Currently, Reek uses `Parser::CurrentRuby` to determine which Ruby version to parse when analyzing code, so it always chooses the installed Ruby version's parser. Under the Code Climate engine, this means that it will always choose the parser for Ruby version `2.6`, because that's the version that is installed in the `Dockerfile`.
To let users choose what Ruby version they want to use reek under, expose a new config attribute "target_ruby_version". This overrides the Reek::Source::SourceCode.default_parser method to use whichever parser version the user specifies.
With `.codeclimate.yml` looking like this:
```yaml
engines:
reek:
enabled: true
config:
target_ruby_version: "2.6.8"
```
The logic will use the first two digits of the chosen version to determine which …
> Code Climate: add config "target_ruby_version" to support different versions of Ruby syntax

- reek.gemspec
rexml has been removed from default gems since Ruby 3.0. https://www.ruby-lang.org/en/news/2020/12/25/ruby-3-0-0-released/
To use rexml, it should be added as runtime dependency. https://github.com/troessner/reek/blob/v6.1.4/lib/reek/report/xml_report.rb#L13
Since rexml is depended from rubocop and kramdown that are only development dependencies, all tests are passed on CI.
> Add missing dependency rexml

- README.md
1.) Fixes the build status badge
2.) Removes the two badges for http://ruby-gem-downloads-badge.herokuapp.com/reek?type=total, because sadly, that project seems to be offline permanently. See [here](https://github.com/bogdanRada/ruby-gem-downloads-badge/issues/7) for the issue. I couldn't find a replacement for this. shields.io seems like a good candidate but it doesn't have a rubygems integration as far as I can see.
> Fix the badges in our README.

- lib/reek/ast/sexp_extensions/send.rb
- spec/reek/ast/sexp_extensions_spec.rb
- spec/reek/smell_detectors/module_initialize_spec.rb
Fixes #1682
- Make `Reek::AST::SexpExtensions::SendNode.module_creation_receiver?` private
- Recognize that `Data.define` creates a new class
> Treat Data.define as a class definition

- tasks/test.rake
I was reading the [Developing Reek Contributing](https://github.com/JuanVqz/reek?tab=readme-ov-file#developing-reek--contributing)
to understand how `reek` works, then run the `rake console` and saw the `warning` message.
```ruby
➜  reek git:(master) be rake console
WARNING: consider using an array rather than a space-delimited string with cucumber_opts to avoid undesired behavior.
```
after making it an array the `warning` was gone, let's see if that works for you.
> Fix cucumber_opts warning

- lib/reek/smell_detectors/instance_variable_assumption.rb
- spec/reek/smell_detectors/instance_variable_assumption_spec.rb
Can you please have a look?
I hope this fixes #1492
What this basically does is look up through all the initializers if it matches the `ivasgn` to consider it instance variable assumption.
> Fix Instance Variable Assumption false positive

- CONTRIBUTING.md
While reading the contributing file, noticed the https://www.relishapp.com page is down. It might be because Heroku removed free servers some time ago.
> Remove non working link

- docs/defaults.reek.yml
- lib/reek/smell_detectors/nested_iterators.rb
- spec/reek/smell_detectors/nested_iterators_spec.rb
Fixes #1490
I've added `Tempfile.create` to the list of ignored iterators and added a spec for it.
I'm submitting the PR to also get some feedback on the implementation. The specs all pass but it fails on the manual method dispatch code smell.
I tried searching for alternative ways to implement this without using `respond_to?` but didn't really find anything satisfactory, and if I don't test for that beforehand, many specs fail on exceptions because the `exp` object lacks the `receiver` method. Feedback on how to fix this would be most welcome!
Otherwise, I hope this is useful!
> Add `Tempfile.create` to ignored iterators list

- README.md
Unfortunately [this nice little service](https://github.com/bogdanRada/ruby-gem-downloads-badge) is now defunct, so let's at least add a static badge. And yeah, it's a shameless plug.
> Add downloads badge.

- .github/workflows/ruby.yml
- Gemfile
- lib/reek/documentation_link.rb
- spec/reek/documentation_link_spec.rb
- Fix subject URL generation on Ruby 3.3
- Add bigdecimal gem to silence warnings
- Build on Ruby 3.3 in CI
> Add support for Ruby 3.3

- README.md
I just stumbled across the Gem, but was surprised that Ruby 3.2 and 3.3 were not among the supported versions. I then found out from the changelog that they are.
Let's update the readme so that no one else is put off. 🙂
> Fix supported Ruby versions in the readme

- reek.gemspec
As per #1627, Yard can't process Reek because `docs/yarn_plugin.rb` is missing. It's not included in the Gem, so this PR adds it to correct this error.
This was reported upstream in
https://github.com/lsegal/yard/issues/1462, but it seems that it either wasn't, or people were happy enough with the workaround (touching the missing file in the Gem's installed location). The workaround doesn't work when using `asdf`/`mise` with [default
Gems](https://mise.jdx.dev/lang/ruby.html#default-gems). If Yard's automatic documentation is enabled (`yard config --gem-install-yri`) then the Ruby build fails.
> Fix Reek installation issue when Yard is installed

- Gemfile
See the commit messages for more details.
- Remove unused `rubocop-rspec_rails` dependency
- Require latest simplecov version
- Remove development dependency on bigdecimal
- Explain the need for redcarpet
> Clean up development dependencies

- reek.gemspec
Using add_runtime_dependency is soft-deprecated and now flagged by RuboCop.
> Replace soft-deprecated runtime dependency specification

- reek.gemspec
This will be needed with Ruby 3.5 and silences a warning in the mean time. Ideally, this would be part of the dependencies of dry-schema via dry-core. Once dry-core depends on logger, the direct dependency can be removed.
> Add explicity dependency on logger

- Gemfile
Doing this semi-manually since dependebot is erroring out.
- Update rubocop to version 1.66.1
- Update rubocop-performance to version 1.22.1
> Update RuboCop dependencies

- README.md
- features/command_line_interface/options.feature
- lib/reek/cli/options.rb
- lib/reek/report.rb
- lib/reek/report/github_report.rb
- spec/reek/report/github_report_spec.rb
How about adding `reek --format github` CLI option, like `rubocop --format github` or `brakeman --format github`?
This would make it very convenient for users in GitHub Actions, as they would be able to see violations on pull request diff page and GitHub Checks page.
> Add `--format github` option

- .gitignore
- Gemfile
- README.md
- features/support/env.rb
- spec/spec_helper.rb
- tasks/console.rake
Straight irb is now good enough for debugging.
> Remove dependency on pry

- reek.gemspec
Dry-rb follows SemVer, so there is no need to lock the version to 1.13.x. This change will allow version 1.14.0 to be used on Ruby 3.1 and up.
> Loosen dependency on dry-schema

- Gemfile
This line was needed to help Bundler pick the correct activesupport version, but Reek no longer has that dependency.
> Remove obsolete ruby version specification from Gemfile

- Gemfile
This doesn't change much, but may make Dependabot not fail anymore.
> Simplify Gemfile

- Gemfile
The plural form is documented, so maybe switching will finally make dependabot work. Also, it's neater to follow the docs.
See https://bundler.io/man/gemfile.5.html#PLATFORMS.
> Use documented form of platform syntax in Gemfile

- reek.gemspec
Version 3.0 of the rainbow gem came out in 2017. There is no need to support using Reek with version 2.x.
> Require Rainbow 3.x
