features/rake_task/rake_task.feature, lib/reek/rake/task.rb
This fixes #326 - I basically rewrote the whole task more or less.
See comments in the diff for further explanation.
=> Revise rake task.

lib/reek/core/smell_repository.rb, lib/reek/smells/smell_detector.rb, spec/reek/core/smell_repository_spec.rb
Fixes https://github.com/troessner/reek/compare/refactor-smell-repository?expand=1#diff-df382c1a7be57c0d63dd0813c69367e9L12
=> Refactor SmellRepository.

lib/reek/source/sexp_extensions.rb, spec/reek/smells/nested_iterators_spec.rb
=> Make NestedIterator not break when iterator is called on super.

assets/html_output.html.erb
=> Fix generating HTML report

README.md
=> Correct output format options shown in README

features/command_line_interface/options.feature, features/command_line_interface/smells_count.feature, features/command_line_interface/stdin.feature, features/configuration_files/masking_smells.feature, features/configuration_files/overrides_defaults.feature, features/rake_task/rake_task.feature, features/reports/reports.feature, features/reports/yaml.feature, features/ruby_api/api.feature, features/samples.feature
=> Remove cucumber annotations

features/command_line_interface/options.feature, features/command_line_interface/smell_selection.feature, features/command_line_interface/smells_count.feature, features/command_line_interface/stdin.feature, features/configuration_files/masking_smells.feature, features/rake_task/rake_task.feature, features/reports/reports.feature, features/step_definitions/reek_steps.rb, lib/reek/cli/report/report.rb
=> If there is any output, make sure it ends with a newline

.rubocop.yml, features/step_definitions/reek_steps.rb, features/support/env.rb, lib/reek/cli/options.rb, lib/reek/cli/report/formatter.rb, lib/reek/cli/report/location_formatter.rb, lib/reek/smells/feature_envy.rb, lib/reek/smells/smell_detector.rb, lib/reek/source/sexp_extensions.rb, lib/reek/source/sexp_node.rb, lib/reek/spec.rb, lib/reek/spec/should_reek.rb, lib/reek/spec/should_reek_of.rb, lib/reek/spec/should_reek_only_of.rb, lib/reek/version.rb, reek.gemspec
Fixes all the Style/Documentation offenses.
=> Document Modules

lib/reek/source/sexp_extensions.rb, spec/reek/smells/uncommunicative_variable_name_spec.rb
=> Handle shadow block arguments

lib/reek/source/sexp_extensions.rb, spec/reek/smells/nested_iterators_spec.rb
=> Make NestedIterators handle super with arguments

CONTRIBUTING.md
Fixes #423. Let me know what you think / where to take it from here. :)
=> First cut of contribution guidelines

.travis.yml
I wouldn’t mind getting these if it’s all the same to you. :)
=> Add @chastell to Travis notifications

config/defaults.reek, features/samples.feature, lib/reek/core/method_context.rb, lib/reek/smells/feature_envy.rb, lib/reek/smells/utility_function.rb, lib/reek/source/sexp_extensions.rb, spec/reek/cli/text_report_spec.rb, spec/reek/smells/feature_envy_spec.rb, spec/reek/smells/utility_function_spec.rb
=> Separate feature envy from utility function

lib/reek/spec.rb, spec/reek/spec/should_reek_of_spec.rb, spec/reek/spec/should_reek_only_of_spec.rb, spec/reek/spec/should_reek_spec.rb, spec/spec_helper.rb
https://github.com/troessner/reek/pull/451/files#r28644971
=> Move spec.rb back to top level.

CHANGELOG, README.md, features/command_line_interface/options.feature, lib/reek/cli/option_interpreter.rb, lib/reek/cli/options.rb, lib/reek/cli/report/report.rb, spec/reek/cli/xml_report_spec.rb, spec/samples/checkstyle.xml
GitFlow style pull request for #449 . Hopefully first ever GifFlow based Reek pull request will be finally merged :)
=> Added Checkstyle format XML report support

docs/API.md
The file api.md inside docs folder contain instruction to run reek inside a ruby app.
=> Added instruction to use reek in ruby code

lib/reek/smells/attribute.rb, spec/reek/smells/attribute_spec.rb
this fixes the TODO in the AttributeSmell.
if this gets merged, the wiki needs to get updates too.
https://github.com/troessner/reek/wiki/Attribute
=> don’t track private methods in the Attributes smell

lib/reek/core/examiner.rb
=> Explain load order issue

lib/reek/core/reference_collector.rb, spec/reek/core/reference_collector_spec.rb
I was travelling when https://github.com/troessner/reek/pull/487 was reviewed, so this fixes my minor nitpick for that. :)
=> Refactor ReferenceCollector call counting

CHANGELOG, features/samples.feature, lib/reek/sexp/sexp_extensions.rb, lib/reek/version.rb, spec/reek/smells/boolean_parameter_spec.rb, spec/reek/smells/uncommunicative_parameter_name_spec.rb, spec/samples/ruby21_syntax.rb, spec/samples/unusual_syntax.rb
Fixes #502.
Basing this off master as it's a bug fix.
=> Hotfix: Handle array decomposition

lib/reek/cli/warning_collector.rb, lib/reek/core/examiner.rb, spec/reek/cli/warning_collector_spec.rb
WarningCollector had nothing to do with anything else in /core but rather with /cli.
=> Move WarningCollector to /cli.

lib/reek/source/source_locator.rb, spec/reek/source/source_locator_spec.rb, spec/samples/source_with_non_ruby_files/gibberish, spec/samples/source_with_non_ruby_files/python_source.py, spec/samples/source_with_non_ruby_files/uncommunicative_parameter_name.rb
Not sure if this is urgent (I'd expect most scanned directories to be "clean") but I'd rather get this out and release 3.0.2 immediately.
Pinging @mvz and @chastell for a quick review.
=> Only use ruby source files.

.rubocop.yml, lib/reek/configuration/app_configuration.rb, lib/reek/report/formatter.rb, lib/reek/smells/nested_iterators.rb
=> Configure MultilineOperationIndentation cop

lib/reek/ast/sexp_extensions.rb, spec/reek/smells/utility_function_spec.rb
Re-opened coming from #541 since we'll drop gitflow.
=> Recognize singleton methods defined via module function.

CONTRIBUTING.md
=> Update contributing document: Get rid of gitflow.

lib/reek/context/module_context.rb, lib/reek/smells/irresponsible_module.rb, spec/reek/smells/irresponsible_module_spec.rb
Two commits, fixing two issues: #485 and #573.
=> Improve IrresponsibleModule

lib/reek/report/heading_formatter.rb
Allows YARD to find the method during doc generation.
=> Ensure presence of overrideable method

features/reports/reports.feature, lib/reek/report/formatter.rb
=> Fix wiki-link cli option.

lib/reek/configuration/app_configuration.rb, spec/reek/configuration/app_configuration_spec.rb, spec/reek/source/source_locator_spec.rb
HOW ABOUT A HAIKU TRIBUTE TO HALF AN HOUR OF DEBUGGING
singleton config
blows up simple tests which pass
in isolatiooon
:tada:
=> Actually reset AppConfiguration

lib/reek/report/report.rb, spec/reek/report/html_report_spec.rb
=> HTMLReport#show: print to stdout like all the other reports

CHANGELOG.md, docs/Basic-Smell-Options.md, docs/Command-Line-Options.md, lib/reek/source/source_code.rb, lib/reek/source/source_locator.rb, spec/reek/code_comment_spec.rb, spec/reek/source/source_locator_spec.rb
=> Capitalise ‘Ruby’ properly

config/defaults.reek, docs/Too-Many-Instance-Variables.md, features/samples.feature, lib/reek/smells/too_many_instance_variables.rb, spec/reek/smells/too_many_instance_variables_spec.rb
Decrease it from 9 to 4, since 9 is wayyyyy too high.
=> Update TooManyInstanceVariables default.

config/defaults.reek, features/samples.feature, lib/reek/smells/too_many_methods.rb
=> Update TooManyMethods default value to 15.

docs/API.md, lib/reek/examiner.rb, lib/reek/smells/smell_detector.rb
=> Update API docs.

spec/reek/ast/node_spec.rb, spec/reek/ast/sexp_extensions_spec.rb, spec/reek/ast/sexp_formatter_spec.rb, spec/reek/context/code_context_spec.rb, spec/reek/context/method_context_spec.rb, spec/reek/context/singleton_method_context_spec.rb, spec/reek/smells/class_variable_spec.rb, spec/spec_helper.rb
Aaaaaaand we get rid of one smell warning: UncommunicativeMethodName! :)
=> Refactor spec_helper.

CHANGELOG.md, lib/reek/code_comment.rb
So .. #654 got merged but not released so I'm making a new PR for master to get this in the next release.
=> Ensure full psych is loaded

docs/Too-Many-Methods.md
=> Update max_methods default value in the docs

lib/reek/cli/option_interpreter.rb, lib/reek/context/code_context.rb, lib/reek/report/formatter.rb, lib/reek/report/report.rb, lib/reek/smells/nil_check.rb, lib/reek/smells/smell_warning.rb, lib/reek/source/source_code.rb, lib/reek/spec.rb, lib/reek/spec/should_reek.rb, lib/reek/tree_dresser.rb, spec/reek/context/code_context_spec.rb, spec/reek/report/html_report_spec.rb, spec/reek/source/source_code_spec.rb, spec/reek/spec/should_reek_spec.rb
I started to work on the ‘switch reek to keyword arguments’ idea. Let me know whether the `Report` example is the right direction.
I also added the ‘work in progress’ label, as I don’t really like pseudo-tags in PR names – but if you’re fond of ‘[WIP]’ then I’ll cave in. ;)
=> Switch to keyword arguments

lib/reek/rake/task.rb
=> Fix file list as argument in rake task.

CHANGELOG.md, lib/reek/version.rb
Quick review would be appreciated @mvz && @chastell  - i'd then release right away.
=> Prepare 3.3.1 release.

features/command_line_interface/smell_selection.feature
=> Explicitely test combination of config and --smell option

features/step_definitions/sample_file_steps.rb, spec/reek/smells/smell_repository_spec.rb
=> Spec and cuke clean ups

lib/reek/ast/node.rb, lib/reek/ast/object_refs.rb, lib/reek/ast/sexp_extensions.rb, lib/reek/configuration/configuration_file_finder.rb, lib/reek/report/formatter.rb, lib/reek/report/report.rb, lib/reek/smells/smell_warning.rb, lib/reek/source/source_code.rb
Ladies and gentlemen,
may I present to you the ultimate "Make reek smell-free" pull request!
This little honeybadger you see below is still in its infancy but fixes already a dozen warnings (or disables them rightfully).
I won't stop till I drop and then we can finally use "rake test:quality" on travis!
=> Fix a bunch of smells.

config/defaults.reek, docs/Uncommunicative-Module-Name.md, features/samples.feature, lib/reek/smells/smell_configuration.rb, lib/reek/smells/uncommunicative_module_name.rb, spec/reek/smells/uncommunicative_module_name_spec.rb
Follow-up to #691 
Adressed all comments - please re-review.
=> Refactor UncommunicativeMethodName.

README.md, docs/Smell-Suppression.md
I think smell detector configuration via comments is one of THE coolest features we actually have in `reek`.
Let's advertise this more!
This PR adds more examples and explanations on how to use it.
=> Update "smell suppression" docs.

CONTRIBUTING.md, docs/style-guide.md
Follow-up from our discussion in #612
=> Add first version of our style guide to contributing.md.

lib/reek/configuration/app_configuration.rb, lib/reek/configuration/configuration_validator.rb, lib/reek/configuration/default_directive.rb, lib/reek/configuration/directory_directives.rb, spec/reek/configuration/app_configuration_spec.rb
Fixes #694.
I have some follow-up ideas for this but I'll make that a separate pull request.
=> Unify config loading mechanisms

docs/Nested-Iterators.md, features/configuration_files/directory_specific_directives.feature, features/samples.feature, lib/reek/ast/sexp_extensions.rb, lib/reek/smells/nested_iterators.rb, spec/factories/factories.rb, spec/reek/smells/nested_iterators_spec.rb
Fixes #685 - ready for review!
=> Ignore iterators without block arguments for NestedIterators.

config/cucumber.yml
I guess nobody's using this. So let's kill it.
Bonus points: Once #726 is merged we can kill the whole directory. Less complexity, yikes!
=> Remove unused cucumber config.

tasks/configuration.rake
=> Add missing description to Rake task.

README.md
=> Use SVG travis badge [ci skip]

lib/reek/cli/application.rb, lib/reek/cli/options.rb, lib/reek/context/code_context.rb, spec/reek/cli/options_spec.rb
=> Remove unused code.

lib/reek/context/attribute_context.rb, lib/reek/context/code_context.rb, lib/reek/tree_walker.rb, spec/reek/smells/attribute_spec.rb
#751
- Create new AttributeContext to handle attributes
- Make AttributeContext use the parent expression's comment
=> Make Attribute respect suppressing comments

CHANGELOG.md, lib/reek/version.rb
=> Prepare 3.6 release.

docs/API.md
Hopefully this will save us some trouble in the future...
=> Explain that smell messages are not part of our API.

lib/reek/ast/reference_collector.rb, spec/reek/ast/reference_collector_spec.rb, spec/reek/smells/utility_function_spec.rb
=> Count super with arguments as a reference to self

features/command_line_interface/basic_usage.feature, features/command_line_interface/options.feature, features/command_line_interface/smell_selection.feature, features/command_line_interface/smells_count.feature, features/command_line_interface/stdin.feature, features/configuration_files/directory_specific_directives.feature, features/configuration_files/masking_smells.feature, features/configuration_loading.feature, features/programmatic_access.feature, features/rake_task/rake_task.feature, features/reports/json.feature, features/reports/reports.feature, features/reports/yaml.feature, features/samples.feature, lib/reek/cli/options.rb, lib/reek/cli/warning_collector.rb, lib/reek/report/formatter.rb, lib/reek/smells/smell_warning.rb, spec/reek/report/code_climate_report_spec.rb, spec/reek/report/json_report_spec.rb, spec/reek/report/yaml_report_spec.rb, spec/reek/smells/smell_warning_spec.rb, spec/samples/checkstyle.xml
This is an attempt to fix #748 as per discussion therein.
=> Simpler output

README.md, lib/reek/configuration/app_configuration.rb, spec/reek/configuration/app_configuration_spec.rb
=> Reverse merge default directives into directory directives.

lib/reek/ast/object_refs.rb, lib/reek/context/code_context.rb, lib/reek/smells/feature_envy.rb, spec/reek/ast/object_refs_spec.rb
I'd appreciate a speedy review @mvz && @chastell since this is part of my ongoing for refactoring TreeWalker, his family, his friends and his colleagues.
=> Refactor ObjectRefs.

spec/reek/cli/input_spec.rb
increasing test coverage for `input.rb` from 0% to 100% for given class
=> adding test for cli/input.rb

lib/reek/context/code_context.rb, lib/reek/context/statement_counter.rb, lib/reek/context_builder.rb, lib/reek/smells/too_many_statements.rb, lib/reek/smells/utility_function.rb, spec/reek/context_builder_spec.rb, spec/reek/smells/too_many_statements_spec.rb
This bad boy is ready for review!
=> Move statement counting into a proper object.

tasks/console.rake
Derived from #795 but now with appropriate commit message and branch name.
=> Add Rake task for console.

CHANGELOG.md, docs/Code-Smells.md, lib/reek/version.rb
@chastell && @mvz whoever merges this, can you please release right away as well?
=> Bump version to 3.8.0.

features/configuration_files/directory_specific_directives.feature, lib/reek/configuration/configuration_validator.rb, spec/reek/configuration/directory_directives_spec.rb, spec/reek/configuration/excluded_paths_spec.rb
=> Don't raise on missing directory for directive.

README.md
=> Add UnusedPrivateMethod configuration for our "Working with Rails" sample

README.md
Hi!
I've create a [SublimeLinter](http://www.sublimelinter.com/en/latest/) [plugin](https://packagecontrol.io/packages/SublimeLinter-contrib-reek) for reek. I thought it would be nice to add it to the `Readme.md`
=> Add SublimeLiner plugin to Readme.md

lib/reek/ast/sexp_extensions/methods.rb, lib/reek/ast/sexp_extensions/send.rb, lib/reek/context/attribute_context.rb, lib/reek/context/code_context.rb, lib/reek/context/ghost_context.rb, lib/reek/context/method_context.rb, lib/reek/context/module_context.rb, lib/reek/context/root_context.rb, lib/reek/context/singleton_attribute_context.rb, lib/reek/context/singleton_method_context.rb, lib/reek/context/visibility_tracker.rb, lib/reek/context_builder.rb, lib/reek/smells/utility_function.rb, spec/reek/context/code_context_spec.rb, spec/reek/context/ghost_context_spec.rb, spec/reek/context/module_context_spec.rb, spec/reek/context_builder_spec.rb, spec/reek/smells/attribute_spec.rb, spec/reek/tree_dresser_spec.rb
=> Fix handling of visibility modifiers

lib/reek/ast/sexp_extensions/constant.rb, lib/reek/ast/sexp_extensions/module.rb, spec/reek/ast/sexp_extensions_spec.rb
=> Fetch a module's name from the source

lib/reek/context/method_context.rb, spec/reek/context_builder_spec.rb
=> Handle nested method contexts

.codeclimate.yml, .dockerignore, Dockerfile, bin/code_climate_reek, engine.json, lib/reek/report/code_climate/code_climate_configuration.yml, lib/reek/report/code_climate/code_climate_formatter.rb, lib/reek/report/formatter.rb, lib/reek/report/report.rb, reek.gemspec, spec/reek/report/code_climate_formatter_spec.rb, spec/reek/report/code_climate_report_spec.rb
References: 
* [Engine example](http://blog.codeclimate.com/blog/2015/07/07/build-your-own-codeclimate-engine/)
* [Spec](https://github.com/codeclimate/spec)
=> Add CodeClimate Docker integration.

.codeclimate.yml, lib/reek/report/code_climate/code_climate_configuration.yml, spec/reek/report/code_climate_formatter_spec.rb, spec/reek/report/code_climate_report_spec.rb
This adds remediation points and content to the Code Climate reporter, and adds Ruby files in the ratings paths section of the `.codeclimate.yml` file so this repo generates grades on Code Climate.
=> Descriptions and remediation points

lib/reek/ast/sexp_extensions/send.rb, spec/reek/ast/sexp_extensions_spec.rb, spec/reek/smells/irresponsible_module_spec.rb
=> Handle any receiver in SendNode#module_creation_receiver?

.gitignore, .simplecov, Gemfile, lib/reek/cli/application.rb, lib/reek/cli/option_interpreter.rb, lib/reek/cli/reek_command.rb, spec/reek/cli/application_spec.rb, spec/reek/cli/reek_command_spec.rb, spec/reek/rake/task_spec.rb, tasks/test.rake
This can help us find dead or untested code.
=> Introduce SimpleCov for specs

reek.gemspec
=> Bump parser.

lib/reek/smells/smell_repository.rb, lib/reek/spec/should_reek_of.rb, spec/reek/spec/should_reek_of_spec.rb
=> Improve reek of

.travis.yml, README.md, reek.gemspec
#868 - removing the keyword arg hack will happen in a separate PR
=> Drop 2.0 compatibiliy.

.rubocop.yml, lib/reek/ast/object_refs.rb, lib/reek/context/visibility_tracker.rb, lib/reek/smells/nested_iterators.rb, lib/reek/smells/smell_warning.rb, lib/reek/smells/uncommunicative_method_name.rb, lib/reek/smells/uncommunicative_module_name.rb, lib/reek/smells/uncommunicative_parameter_name.rb, lib/reek/source/source_code.rb, lib/reek/spec/smell_matcher.rb
Precondition for this one is #869
=> Remove raise hack for default args

features/configuration_files/exclude_directives.feature, features/configuration_files/unused_private_method.feature, lib/reek/smells/unused_private_method.rb, spec/reek/smells/unused_private_method_spec.rb
Getting started with fixing #816
=> Fix `disable UnusedPrivateMethod via `exclude` in configuration.

spec/spec_helper.rb
factory_girl is now at 4.7.0 which makes #899 fail
=> Remove factory_girl warning.

docs/Attribute.md, docs/Boolean-Parameter.md, docs/Class-Variable.md, docs/Command-Line-Options.md, docs/Control-Couple.md, docs/Control-Parameter.md, docs/Data-Clump.md, docs/Duplicate-Method-Call.md, docs/Irresponsible-Module.md, docs/Large-Class.md, docs/Long-Parameter-List.md, docs/Long-Yield-List.md, docs/Nested-Iterators.md, docs/Nil-Check.md, docs/Prima-Donna-Method.md, docs/Repeated-Conditional.md, docs/Too-Many-Instance-Variables.md, docs/Too-Many-Methods.md, docs/Too-Many-Statements.md, docs/Uncommunicative-Method-Name.md, docs/Uncommunicative-Module-Name.md, docs/Uncommunicative-Name.md, docs/Uncommunicative-Parameter-Name.md, docs/Uncommunicative-Variable-Name.md, docs/Unused-Parameters.md, docs/Unused-Private-Method.md, docs/Utility-Function.md
* Document `--smell` option
* Improve code smell documentation
=> Documentation improvements

lib/reek/configuration/app_configuration.rb, lib/reek/configuration/default_directive.rb, lib/reek/spec/should_reek_of.rb, spec/reek/smells/unused_private_method_spec.rb, spec/reek/spec/should_reek_of_spec.rb
=> Automatically enable smell in reek_of matcher

lib/reek/context/module_context.rb, spec/reek/smells/unused_private_method_spec.rb
=> Stop UnusedPrivateMethod getting confused by nested classes

lib/reek/spec/should_reek_of.rb, spec/reek/smells/duplicate_method_call_spec.rb, spec/reek/smells/nested_iterators_spec.rb, spec/reek/smells/uncommunicative_method_name_spec.rb, spec/reek/smells/uncommunicative_module_name_spec.rb, spec/reek/smells/uncommunicative_parameter_name_spec.rb, spec/reek/smells/unused_private_method_spec.rb, spec/reek/smells/utility_function_spec.rb, spec/reek/spec/should_reek_of_spec.rb
=> reek_of with_config

README.md
Hi
I like your gem so much and am Emacs user.
There is no plugin for Reek so I have created a simple package for interfacing Reek inside emacs.
Cheers
=> Add emacs plugin page

README.md
Our README is pretty big and kind of unwieldy for new users. 
This ToC hopefully makes it easier for people to browse our README.
=> Add ToC to README.

.travis.yml
=> Make build steps depend on each other.

docs/Duplicate-Method-Call.md
- remove empty parameter list
- improve suggestion
=> Improves Duplicate-Method-Call.md [ci skip]

.travis.yml, Rakefile, tasks/ataru.rake, tasks/mutant.rake
Also add tasks for ataru and mutant.
=> Add `ci` Rake task.

tasks/mutant.rake
=> Do not run `mutant` on master.

CHANGELOG.md, lib/reek/version.rb
=> Bump version to 4.1.0.

Gemfile, lib/reek/ast/sexp_extensions/lambda.rb, spec/reek/ast/sexp_extensions_spec.rb
=> Checking lambda should not raise error

lib/reek/ast/sexp_extensions/lambda.rb, lib/reek/ast/sexp_extensions/module.rb, spec/reek/ast/sexp_extensions_spec.rb, spec/reek/smells/subclassed_from_core_class_spec.rb
=> Ensure superclass is only returned for class creation calls

Gemfile
This stops me from being bitten by https://github.com/bundler/bundler/issues/4758
=> Update simplecov dependency

lib/reek/ast/node.rb, lib/reek/context/statement_counter.rb, spec/reek/ast/node_spec.rb, spec/reek/context/statement_counter_spec.rb
One less generic exception raised (#809).
=> Simplify StatementCounter

lib/reek/smells/too_many_constants.rb, spec/reek/smells/too_many_constants_spec.rb
=> Fix TooManyConstants for outer module when inner module suppress

README.md
=> Revamp our badge setup.

defaults.reek
This is an automatically generated change.
=> Update default config for UtilityFunction

spec/reek/smells/nested_iterators_spec.rb
=> Add specs for NestedIterators with safe navigation

CONTRIBUTING.md
cc @tomdalling (excellent article!)
=> Improve our contributing guidelines.

lib/reek/examiner.rb, spec/reek/examiner_spec.rb
=> Make Reek more resilient on incomprehensible source.

Gemfile, lib/reek/smells/smell_warning.rb
=> Update rubocop and autocorrect offense

docs/Nil-Check.md, lib/reek/smells/nil_check.rb, spec/reek/smells/nil_check_spec.rb
#749.
This also improves NilCheck output when multiple lines have a nil check.
=> Detect safe navigation operator as nil check

docs/Instance-Variable-Assumption.md
=> Add docs for InstanceVariableAssumption.

docs/Instance-Variable-Assumption.md
=> Update InstanceVariableAssumption docs.

README.md, docs/Code-Smells.md
=> Update code smell docs.

CONTRIBUTING.md, docs/How-To-Write-New-Detectors.md
=> Document how to write new detectors.

lib/reek/smells/boolean_parameter.rb, lib/reek/smells/class_variable.rb, lib/reek/smells/instance_variable_assumption.rb, lib/reek/smells/prima_donna_method.rb, lib/reek/smells/unused_private_method.rb, spec/reek/smells/instance_variable_assumption_spec.rb, spec/reek/smells/prima_donna_method_spec.rb, spec/reek/smells/unused_private_method_spec.rb
=> Make parameter handling in detectors consistent.

features/configuration_via_source_comments/erroneous_source_comments.feature, lib/reek/ast/node.rb, lib/reek/code_comment.rb, lib/reek/context/code_context.rb, lib/reek/context/module_context.rb, lib/reek/errors.rb, lib/reek/examiner.rb, lib/reek/rake/task.rb, lib/reek/smells/smell_detector.rb, spec/factories/factories.rb, spec/reek/ast/node_spec.rb, spec/reek/code_comment_spec.rb, spec/reek/examiner_spec.rb, spec/reek/smells/smell_detector_spec.rb
=> Fail properly on bad configuration comments.

features/configuration_via_source_comments/well_formed_source_comments.feature
I know we want to cut down on cucumber features but for proper integration testing that tests the full stack a la:
"creating source file" -> "add configuration" -> "run Reek" -> "validate output"
cucumber is and probably will be our weapon of choice for the time to come.
I believe that configuration via source comments was not properly tested at all except for a couple of spot checks in our detector specs here and there, but that was is it.
This is an attempt to fix this.
A fast review and merge would be appreciated because this is the base for my current work on #1069
=> Properly feature test configuration via source comments.

lib/reek/examiner.rb, spec/reek/examiner_spec.rb
=> Improve how we handle internal error in detectors.

docs/Style-Guide.md
=> Update styleguide with data types.

README.md, features/todo_list.feature, lib/reek/cli/command/todo_list_command.rb
Fixes #916 - ready for review!
=> Create a fresh todo file on every run.

docs/How-reek-works-internally.md, lib/reek/examiner.rb, lib/reek/smells/detector_repository.rb, spec/reek/examiner_spec.rb, spec/reek/smells/detector_repository_spec.rb, tasks/configuration.rake
=> Rename SmellRepository to DetectorRepository.

.rubocop.yml, CONTRIBUTING.md, features/command_line_interface/basic_usage.feature, features/command_line_interface/show_progress.feature, features/command_line_interface/smell_selection.feature, features/command_line_interface/smells_count.feature, features/command_line_interface/stdin.feature, features/configuration_files/accept_setting.feature, features/configuration_files/directory_specific_directives.feature, features/configuration_files/exclude_directives.feature, features/configuration_files/masking_smells.feature, features/configuration_files/mix_accept_reject_setting.feature, features/configuration_files/reject_setting.feature, features/configuration_files/unused_private_method.feature, features/configuration_loading.feature, features/configuration_via_source_comments/erroneous_source_comments.feature, features/configuration_via_source_comments/well_formed_source_comments.feature, features/rake_task/rake_task.feature, features/reports/reports.feature, features/samples.feature, features/todo_list.feature, lib/reek/cli/options.rb, lib/reek/report/formatter/progress_formatter.rb, lib/reek/report/text_report.rb, spec/reek/cli/command/report_command_spec.rb, spec/reek/cli/options_spec.rb, spec/reek/report/formatter/progress_formatter_spec.rb
Implements #1118. Like #1119, but targeting master.
=> Hide progress on non-ttys

features/configuration_via_source_comments/erroneous_source_comments.feature, lib/reek/code_comment.rb, lib/reek/errors/bad_detector_configuration_key_in_comment_error.rb, lib/reek/examiner.rb, lib/reek/smell_detectors/base_detector.rb, spec/reek/code_comment_spec.rb, spec/reek/smell_detectors/base_detector_spec.rb
Hash-tag #long-flight nr.4 ;)
Branched of of #1112 and heavily wip. Please hold off with a review for now.
I'll stop with this one here until we have #1112 merged and continue from there.
=> Validate configuration keys in code comments

.travis.yml, Gemfile
- Update rake to 12.0
- Loosen activesupport dependency
- Tell bundler to respect current Ruby version so it picks the correct version of activesupport
- Ensure latest version of bundler on Travis to make the previous point work there
=> Update build dependencies

Dockerfile
* Bumped Ruby to 2.3.3 (was 2.2.2p95)
* Bumped all gems to their latest versions
=> Bump dependencies for Code Climate engine

docs/Prima-Donna-Method.md, docs/Unused-Private-Method.md, features/command_line_interface/options.feature, lib/reek/cli/options.rb, lib/reek/smell_detectors/prima_donna_method.rb, spec/reek/smell_detectors/prima_donna_method_spec.rb
=> Improve documentation and fix PrimaDonnaMethod detector configuration via comment.

features/configuration_files/exclude_paths_directives.feature, lib/reek/cli/application.rb, spec/reek/cli/application_spec.rb
=> Respect exclude_paths when passing sources on the command line

docs/Nil-Check.md
The logic in this example was backwards.
=> Fix incorrect Nil Check example

Dockerfile, lib/reek/report/code_climate/code_climate_configuration.yml
There is some additional detail in the commit messages. Happy to answer any questions you may have!
=> A few updates for Code Climate

lib/reek/ast/sexp_extensions/arguments.rb, lib/reek/cli/application.rb, lib/reek/spec.rb, spec/factories/factories.rb, spec/reek/context/module_context_spec.rb
* Improve spec by checking actual context name
* Improve documentation for reek_only_of
* Remove some dead code
* Remove unused instance variable
=> Various fixes

CHANGELOG.md, lib/reek/version.rb
=> Bump version to 4.6.0.

README.md
#1198.
This reverts commit e7d20b86c95c97314b5ba5ac303634d183173ec8.
=> Restore explanation of what our default Rake task is doing

docs/Prima-Donna-Method.md
Coming from [issue 1216](https://github.com/troessner/reek/issues/1216)
=> Fix typo in code sample.

CHANGELOG.md, lib/reek/version.rb
=> Bump version to 4.7.0.

lib/reek/context/attribute_context.rb, lib/reek/context/code_context.rb, lib/reek/context/method_context.rb, lib/reek/context/module_context.rb, lib/reek/context/root_context.rb, lib/reek/context/send_context.rb, lib/reek/context_builder.rb, spec/reek/context/code_context_spec.rb, spec/reek/context/ghost_context_spec.rb, spec/reek/context/method_context_spec.rb, spec/reek/context/module_context_spec.rb, spec/reek/context_builder_spec.rb, spec/reek/smell_detectors/unused_private_method_spec.rb, spec/reek/smell_detectors/utility_function_spec.rb
=> Handle private def comment

features/rake_task/rake_task.feature, features/step_definitions/reek_steps.rb, features/support/env.rb, lib/reek/rake/task.rb, spec/reek/rake/task_spec.rb
=> Empower reek_src env var

features/rspec_matcher.feature, lib/reek/configuration/app_configuration.rb, lib/reek/spec.rb
=> Use config file in `reek` matcher

lib/reek/errors/encoding_error.rb, lib/reek/examiner.rb, lib/reek/source/source_code.rb, spec/reek/examiner_spec.rb, spec/reek/source/source_code_spec.rb
Fixes #1262 - still wip though.
=> Handle encoding error when parsing the source

features/locales.feature, lib/reek/source/source_code.rb
=> Handle UTF-8 files in all locales

lib/reek/errors/encoding_error.rb, lib/reek/errors/incomprehensible_source_error.rb, lib/reek/logging_error_handler.rb, spec/reek/examiner_spec.rb
=> Print exception classes

.codeclimate.yml
Cleans up the list of codeclimate issues :-).
=> Add samples directory to CodeClimate exclude paths

CHANGELOG.md
Follow-up for #1287 and other merged features.
=> Add change log entries for unreleased version

.travis.yml, reek.gemspec
We all love random build failures :heart:
=> Don't fiddle with rubygems or bundler

.rubocop.yml, .travis.yml, reek.gemspec
=> Drop Ruby 2.1 support.

README.md, features/configuration_files/directory_specific_directives.feature, lib/reek/configuration/app_configuration.rb, lib/reek/configuration/directory_directives.rb, samples/configuration/full_configuration.reek, spec/reek/configuration/app_configuration_spec.rb, spec/reek/configuration/directory_directives_spec.rb
=> Move directory directives under a special key.

lib/reek/cli/options.rb
Fixes #1334 (except the cukes don't catch it).
=> Fix list output

lib/reek/configuration/configuration_file_finder.rb
Was neither tested in any way nor does it seem to make sense.
=> Remove useless check.

docs/Duplicate-Method-Call.md
=> Update docs for DuplicateMethodCall.

lib/reek/configuration/configuration_file_finder.rb
=> Revert "Remove useless check."

docs/Feature-Envy.md
Fixes #1131 in analogy to #1350
=> Update docs for FeatureEnvy.

spec/reek/configuration/configuration_file_finder_spec.rb
This fixes the specs to actually test what is in the description.
Fixes #1349.
=> Fix nonsensical ConfigurationFileFinder specs

spec/reek/configuration/configuration_file_finder_spec.rb
=> Add simple spec to document nil file behavior

docs/defaults.reek, features/configuration_files/accept_setting.feature, features/configuration_files/directory_specific_directives.feature, features/configuration_files/exclude_directives.feature, features/configuration_files/masking_smells.feature, features/configuration_files/mix_accept_reject_setting.feature, features/configuration_files/reject_setting.feature, features/configuration_files/unused_private_method.feature, features/configuration_loading.feature, features/rspec_matcher.feature, features/todo_list.feature, lib/reek/cli/command/todo_list_command.rb, lib/reek/configuration/app_configuration.rb, lib/reek/configuration/converter.rb, lib/reek/configuration/default_directive.rb, lib/reek/spec/should_reek_of.rb, samples/configuration/accepts_rejects_and_excludes.reek.yml, samples/configuration/full_configuration.reek, samples/configuration/full_mask.reek, samples/configuration/partial_mask.reek, spec/reek/cli/command/todo_list_command_spec.rb, spec/reek/configuration/app_configuration_spec.rb, spec/reek/configuration/configuration_file_finder_spec.rb, spec/reek/configuration/default_directive_spec.rb, tasks/configuration.rake
=> Scope detectors under a specific key in the configuration.

CHANGELOG.md, lib/reek/version.rb
Release from stable reek-4-8 branch.
=> Release reek 4.8.2

.rubocop.yml, features/configuration_files/directory_specific_directives.feature, features/configuration_files/masking_smells.feature, features/configuration_files/schema_validation.feature, features/step_definitions/sample_file_steps.rb, lib/reek/configuration/configuration_file_finder.rb, lib/reek/configuration/converter.rb, lib/reek/configuration/default_directive.rb, lib/reek/configuration/schema.yml, lib/reek/configuration/schema_validator.rb, reek.gemspec, spec/reek/configuration/schema_validator_spec.rb
=> Validate our configuration by using a schema.

lib/reek/ast/node.rb, lib/reek/cli/silencer.rb, lib/reek/configuration/schema_validator.rb, lib/reek/source/source_code.rb, spec/reek/tree_dresser_spec.rb, spec/spec_helper.rb
Shuts up warnings without blanket-suppressing all output.
=> Suppress only warnings from other gems

lib/reek/configuration/configuration_file_finder.rb, spec/reek/configuration/configuration_file_finder_spec.rb
Fixes #1383  - quick review would be great @mvz 
I'd then release 5.0.1 right away.
=> Fix uninitialized constant error.

features/command_line_interface/options.feature, features/reports/json.feature, features/reports/reports.feature, features/reports/yaml.feature
=> Update expected documentation links

.simplecov
=> Improve our simplecov set up.

README.md, docs/Instance-Variable-Assumption.md
=> Update InstanceVariableAssumption docs for Rails context.

CONTRIBUTING.md, README.md, features/configuration_files/exclude_paths_directives.feature, features/configuration_files/schema_validation.feature, features/step_definitions/sample_file_steps.rb, lib/reek/configuration/excluded_paths.rb, lib/reek/source/source_locator.rb, samples/configuration/with_excluded_paths.reek, samples/source_with_exclude_paths/nested/uncommunicative_variable_name.rb, spec/reek/configuration/app_configuration_spec.rb, spec/reek/configuration/excluded_paths_spec.rb, spec/reek/source/source_locator_spec.rb
=> Enable exclusion of single files.

Gemfile
=> Update rubocop-rspec to 1.30.0

.rubocop_todo.yml, spec/reek/configuration/app_configuration_spec.rb
=> Fix hash alignment for AppConfiguration specs

reek.gemspec
Upgraded parser dependency so it supports the latest version.
=> Upgraded parser dependency

Gemfile, features/support/env.rb
* Update to latest aruba release and fix deprecations
* Update factory_bot
* Update rubocop-rspec
=> Update development dependencies

CHANGELOG.md, features/command_line_interface/options.feature, features/reports/json.feature, features/reports/reports.feature, features/reports/yaml.feature, lib/reek/version.rb
=> Prepare v5.3.1.

docs/Duplicate-Method-Call.md
Coming from #1456 I realized that we never really explain why we consider this a smell. We just say it is ;)
=> Extend documentation for DuplicateMethodCall.

lib/reek/source/source_code.rb
=> Use Parser26.

Dockerfile, Gemfile, bin/code_climate_reek, features/command_line_interface/options.feature, features/reports/codeclimate.feature, features/step_definitions/reek_steps.rb, lib/reek/cli/options.rb, lib/reek/report.rb, lib/reek/report/code_climate/code_climate_report.rb, lib/reek/report/simple_warning_formatter.rb, reek.gemspec
=> Isolate code climate dependency

lib/reek/code_comment.rb, lib/reek/errors/legacy_comment_separator_error.rb, lib/reek/smell_detectors/base_detector.rb, spec/reek/code_comment_spec.rb, spec/reek/smell_detectors/base_detector_spec.rb, spec/reek/smell_detectors/missing_safe_method_spec.rb
=> Raise error when legacy code comment format is used

docs/Nil-Check.md, lib/reek/smell_detectors/nil_check.rb, spec/reek/smell_detectors/nil_check_spec.rb
=> Stop reporting NilCheck for safe navigation

README.md
https://github.com/reviewdog/action-reek
=> Add GitHub Action to run reek

lib/reek/configuration/directory_directives.rb, spec/reek/configuration/directory_directives_spec.rb
Proposed solution to address https://github.com/troessner/reek/issues/1540
=> Match absolute paths of directories in .reek.yml

lib/reek/configuration/excluded_paths.rb, spec/reek/configuration/excluded_paths_spec.rb
=> Support glob patterns in exclude_paths

CONTRIBUTING.md
Apparantly there are people who don't know about (fenced) code blocks, and I'm tired of fixing up people's tickets.
=> Add request to use code blocks in issues to CONTRIBUTING.md

reek.gemspec
Hijacking great work #1553, by just fixing minor failure on rubocop.
=> Reduce gem package size

lib/reek/ast/sexp_extensions/arguments.rb, spec/reek/ast/sexp_extensions_spec.rb
=> Support argument forwarding after regular arguments

lib/reek/context/module_context.rb, lib/reek/context/send_context.rb, lib/reek/smell_detectors/unused_private_method.rb, spec/reek/smell_detectors/unused_private_method_spec.rb
Fixes https://github.com/troessner/reek/issues/1515:
=> UnusedPrivateMethod to be detect use of methods via `Method#to_proc`

reek.gemspec
=> Update parser dependency to the 3.2.x series

Gemfile
Dependabot is having an unknown error so I'm updating this one by hand.
=> Update rubocop to version 1.65.0

Gemfile
- Update rubocop to version 1.69.0
- Update rubocop-performance to version 1.23.0
- Update rubocop-rspec to version 3.2.0
=> Update rubocop dependencies
